### PR TITLE
Fix flaky TestConcurrentFetchers_fetchSingle

### LINKED ISSUE #11085: Flaky `TestConcurrentFetchers_fetchSingle/should_return_an_error_response_if_the_Fetch_request_contains_an_error`
[Logs](https://github.com/grafana/mimir/actions/runs/14212346738/job/39821721618?pr=11084#step:8:93):

```
--- FAIL: TestConcurrentFetchers_fetchSingle (0.08s)
    --- FAIL: TestConcurrentFetchers_fetchSingle/should_return_an_error_response_if_the_Fetch_request_contains_an_error (0.03s)
        logger.go:38: 2025-04-02 05:41:00.823465896 +0000 UTC m=+21.680435290 level info msg starting concurrent fetchers start_offset 0 concurrency 1 bytes_per_fetch_request 2147483647
        logger.go:38: 2025-04-02 05:41:00.823491426 +0000 UTC m=+21.680460841 level info component kafka_client msg producing to a new topic for the first time, fetching metadata to learn its partitions topic test-topic
        logger.go:38: 2025-04-02 05:41:00.823566082 +0000 UTC m=+21.680535467 fetcher 0 level error msg received an error while fetching records; will retry after processing received records (if any) duration 13.515µs start_offset 0 end_offset 214748 asked_records 214748 got_records 0 diff_records 214748 asked_bytes 2147483647 got_bytes 0 diff_bytes 2147483647 first_timestamp  last_timestamp  hwm 0 lso 0 err unknown partition leader
        logger.go:38: 2025-04-02 05:41:00.823494528 +0000 UTC m=+21.680463913 level info component kafka_client msg immediate metadata update triggered why forced load because we are producing to a topic for the first time
        logger.go:38: 2025-04-02 05:41:00.827098806 +0000 UTC m=+21.684068201 level info component kafka_client msg done waiting for metadata for new topic topic test-topic
        logger.go:38: 2025-04-02 05:41:00.827162254 +0000 UTC m=+21.684131649 level info component kafka_client msg initializing producer id
        logger.go:38: 2025-04-02 05:41:00.82741792 +0000 UTC m=+21.684387315 level info component kafka_client msg producer id initialization success id 4457468340882392421 epoch 0
        logger.go:38: 2025-04-02 05:41:00.836472957 +0000 UTC m=+21.693442352 fetcher 0 level error msg received an error while fetching records; will retry after processing received records (if any) duration 606.964µs start_offset 0 end_offset 214748 asked_records 214748 got_records 0 diff_records 214748 asked_bytes 2147483647 got_bytes 0 diff_bytes 2147483647 first_timestamp  last_timestamp  hwm 0 lso 0 err fetch request failed with error: UNKNOWN_SERVER_ERROR: The server experienced an unexpected error when processing the request.
        logger.go:38: 2025-04-02 05:41:00.836568976 +0000 UTC m=+21.693538371 fetcher 0 method concurrentFetcher.fetch.attempt level error msg received an error we're not prepared to handle; this shouldn't happen; please report this as a bug err fetch request failed with error: UNKNOWN_SERVER_ERROR: The server experienced an unexpected error when processing the request.
        fetcher_test.go:1055: 
            	Error Trace:	/__w/mimir/mimir/pkg/storage/ingest/fetcher_test.go:966
            	            				/__w/mimir/mimir/pkg/storage/ingest/fetcher_test.go:1055
            	Error:      	Not equal: 
            	            	expected: 0x1
            	            	actual  : 0x2
            	Test:       	TestConcurrentFetchers_fetchSingle/should_return_an_error_response_if_the_Fetch_request_contains_an_error
        logger.go:38: 2025-04-02 05:41:00.84687486 +0000 UTC m=+21.703844254 level info msg stopped concurrent fetchers last_returned_offset -1
FAIL
FAIL	github.com/grafana/mimir/pkg/storage/ingest	96.989s
```

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does

`TestConcurrentFetchers_fetchSingle` is flaky because it races with the fetch run by the fetchers goroutine. Since we want to test `fetchSingle()` in isolation, we shouldn't start the goroutines. In this PR I propose to fix it adding an explicit `Start()` function to `concurrentFetchers`, so we can control when starting them.

#### Which issue(s) this PR fixes or relates to

Fixes #11085

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/storage/ingest/fetcher.go [hunk 1]
```diff
@@ -334,7 +339,9 @@ func newConcurrentFetchers(
 		metrics:                 metrics,
 		minBytesWaitTime:        minBytesWaitTime,
 		lastReturnedOffset:      startOffset - 1,
-		startOffsets:            startOffsetsReader,
+		startOffset:             startOffset,
+		startConcurrency:        concurrency,
```
Comment (pracucci) [inline pkg/storage/ingest/fetcher.go:343]: To reduce signature changes, I preferred to store the `startOffset` and `startConcurrency` on the `concurrentFetchers` struct, and then just read them in the new `Start()` function. `startOffset` gets manipulated in this function too.
