### PR TITLE
fix(ingester): Keep read only when any number of compactions in progress

### LINKED ISSUE #11850: Bug: Ingesters can exit read-only mode during TSDB compactions
### What is the bug?

There is a bug in how Mimir handles TSDB head compaction that was previously reported and partially resolved by https://github.com/grafana/mimir/pull/11664. That PR fixed the issue for TSDB compactions started when the `force` flag is set as an argument to `Ingester.CompactBlocks`. This issue deals with TSDB compactions that are triggered by a tenant's TSDB being idle.

When an ingester has a tenant running TSDB  head compaction, the state of the tenant's `userTSDB` is set to `forceCompacting` ([ref](https://github.com/grafana/mimir/blob/b7ef8854f464ce30e2687040a9b2acf8cd208f76/pkg/ingester/user_tsdb.go#L221)). When a write is sent to a TSDB that is in `forceCompacting`, the write is conditionally rejected if the `forcedCompactionMaxTime` is larger than the push's minimum timestamp. ([ref](https://github.com/grafana/mimir/blob/b7ef8854f464ce30e2687040a9b2acf8cd208f76/pkg/ingester/user_tsdb.go#L484)). Because TSDB compactions triggered by idleness set `forcedCompactionMaxTime` to `math.MaxInt64`, all writes to these DBs will be rejected.

At Grafana Labs, we have observed cases where  the following sequence occurs: 

- A StatefulSet scales down and puts an ingester replica into  `readOnly` mode. 
- After ~1h, the user's TSDB begins a compaction due to idleness. 
    - Note: This process starts between 60m-75m of no-writes due to jitter (see: https://github.com/grafana/mimir/issues/2699).  More precisely, between 1-1.25 * `blocks-storage.tsdb.head-compaction-idle-timeout`.
- Shortly after head compaction begins, the STS scales back up and the replica rejoins the ring in an active state. 

This final step should not be allowed. If multiple zones are compacting due to idleness at the same time, all pushes with series sharded to that ingester will fail. As noted on https://github.com/grafana/mimir/pull/11664.

> read-only mode while a forced compaction is pending or in progress. Leaving read-only mode during the compaction will cause write errors, because writes are blocked.

### What did you think would happen?

The ingester shouldn't be able to leave read-only mode because a `forcedCompaction` (triggered by DB idleness) is in progress. This fails because atomics in `Ingester.compactBlocks` are only set when `force` is set.

### Any additional context to share?

A scale-down and scale-up separated by approx. `head_compaction_idle_timeout` is just one way this bug can appear. Consider the following situation:

- A tenant receives frequent writes from 00:00 to 01:00
- At 01:00, the tenant stops writing all series
- Between 02:05 and 02:10, all three TSDBs begin head compaction. For argument's sake - we'll assume this takes 5m.
- At 2:10, writes restart. With all three zones running compaction, writes will fail until 2/3 finish.
 
This version of the bug may not be resolved in the same way as the version described above.

### PR DESCRIPTION
**Pull request by periklis**
#### What this PR does

This pull request is a refinement of the previous attempt to keep read-only state when any kind of compaction in progress (See #11890).  In contrast the previous PR removed accidentaly the `cortex_ingester_tsdb_forced_compactions_in_progress` metric that is used in downstream alerts.

#### Which issue(s) this PR fixes or relates to

Fixes #11850

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Review by tacole02 — APPROVED** [review]

File: pkg/ingester/downscale.go [hunk 1]
```diff
@@ -52,8 +52,8 @@ func (i *Ingester) PrepareInstanceRingDownscaleHandler(w http.ResponseWriter, r
 		i.circuitBreaker.push.deactivate()
 
 	case http.MethodDelete:
-		// Don't leave read-only mode if there's a forced compaction pending or in progress.
-		if len(i.forceCompactTrigger) > 0 || i.forcedCompactionInProgress.Load() {
+		// Don't leave read-only mode if there is any compaction pending or in progress.
+		if i.numCompactionsInProgress.Load() != 0 {
 			msg := "cannot clear read-only mode while forced compaction is in progress"
```
Comment (pr00se) [inline pkg/ingester/downscale.go]:
```suggestion
			msg := "cannot clear read-only mode while a compaction is pending or in progress"
```

File: pkg/ingester/ingester.go [hunk 2]
```diff
@@ -3301,16 +3311,29 @@ func (i *Ingester) compactionServiceInterval() (firstInterval, standardInterval
 	return
 }
 
+// prepareCompaction is incrementing the atomic counter of the number of compactions in progress.
+// It also exposes a metric tracking the number of compactions in progress.
+// It returns a callback that should be called when the compaction is finished, e.g. in defer statement.
+// This callback is decrementing the atomic counter of the number of compactions in progress.
+func (i *Ingester) prepareCompaction() func() {
```
Comment (pr00se) [inline pkg/ingester/ingester.go]: since we've removed the other metric, do we still need this function? it might be clearer to put the counter increment/decrement directly in the two call sites, rather than have to look up what `prepareCompaction` does.

Comment (periklis) [reply pkg/ingester/ingester.go]: Yes you are absolutely right. It is easier to reason inline with a atomic inc/dec rather than masking this in a separate function with a bad name :)

File: pkg/ingester/downscale.go (hunk 1 above)
Comment (periklis) [reply pkg/ingester/downscale.go]: ack!
