### PR TITLE
Fix panic when using read and write reactive limiters with prioritization

### LINKED ISSUE #13480: Bug: Reactive limiters are causing ingesters to Panic
### What is the bug?

We run Mimir with reactive limiters enabled. When upgrading to Mimir 3, ingesters starts to fail

```
ts=2025-11-07T18:15:41.035013512Z caller=memberlist_client.go:628 level=info msg="memberlist fast-join starting" nodes_found=15 to_join=8
panic: interface conversion: priority.Prioritizer is *reactivelimiter.Prioritizer, not *internal.BasePrioritizer[*github.com/failsafe-go/failsafe-go/adaptivelimiter.queueStats]

goroutine 1 [running]:
github.com/failsafe-go/failsafe-go/adaptivelimiter.(*config[...]).BuildPrioritized(0x4238800?, {0x41f2cc0, 0xc0022a4600})
        /__w/mimir/mimir/vendor/github.com/failsafe-go/failsafe-go/adaptivelimiter/adaptivelimiter.go:351 +0x18a
github.com/grafana/mimir/pkg/util/reactivelimiter.NewWithPriority(0x23?, {0x41a3160?, 0xc0005b01c8?}, 0x1, {0x41f2cc0, 0xc0022a4600})
        /__w/mimir/mimir/pkg/util/reactivelimiter/reactivelimiter.go:75 +0x43
github.com/grafana/mimir/pkg/ingester.newReactiveLimiter(0xc0022a4600?, {0x3973e9a, 0x4}, {0x41a3160?, 0xc0005b01c8?}, {0x41d3e30, 0x6287740}, 0x3973b9e?, 0x4?)
        /__w/mimir/mimir/pkg/ingester/reactivelimiter.go:64 +0x6b
github.com/grafana/mimir/pkg/ingester.newIngesterReactiveLimiter(0xc001ae9008, 0xc001ae9010?, 0xc001ae9078, {0x41a3160, 0xc0005b01c8}, {0x41d3e30, 0x6287740})
        /__w/mimir/mimir/pkg/ingester/reactivelimiter.go:42 +0xd8
github.com/grafana/mimir/pkg/ingester.New({{{{0x397fa02, 0xa}, {0x3982911, 0xb}, {{...}, {...}, {...}, _}, {_, _}}, ...}, ...}, ...)
        /__w/mimir/mimir/pkg/ingester/ingester.go:442 +0x39c
github.com/grafana/mimir/pkg/mimir.(*Mimir).initIngesterService(0xc000726000)
        /__w/mimir/mimir/pkg/mimir/modules.go:746 +0x229
github.com/grafana/dskit/modules.(*Manager).initModule(0xc0005b0798, {0x7ffe38c0b366, 0x8}, 0xc000c4ccf8, 0xc00094f0b0)
        /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136 +0x20c
github.com/grafana/dskit/modules.(*Manager).InitModuleServices(0xc0005b0798, {0xc0007a8230, 0x1, 0x8?})
        /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108 +0xf4
github.com/grafana/mimir/pkg/mimir.(*Mimir).Run(0xc000726000)
        /__w/mimir/mimir/pkg/mimir/mimir.go:1006 +0x36f
main.main()
        /__w/mimir/mimir/cmd/mimir/main.go:235 +0x1010
```

### How to reproduce it?

Run Mimir with the following configuration:

```
      ingester:
        # Enable https://grafana.com/docs/mimir/latest/configure/about-reactive-limiters/ for ingester reliability
        push_reactive_limiter:
          enabled: true
        read_reactive_limiter:
          enabled: true
        # Enable https://grafana.com/docs/mimir/latest/configure/about-ingester-circuit-breakers/ for ingester reliability
        push_circuit_breaker:
          enabled: true
        read_circuit_breaker:
          enabled: true
```

### What did you think would happen?

Ingesters should start without issue

### What was your environment?

Kubernetetes 1.33, Helm

### Any additional context to share?

_No response_

### PR DESCRIPTION
**Pull request by jhalterman**
#### What this PR does

Fixes a panic that happens when push and read reactive limiters are enabled with prioritization.

#### Which issue(s) this PR fixes or relates to

Fixes #13480

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

---

> [!NOTE]
> Fixes a panic by passing the correct prioritizer to `reactivelimiter.NewWithPriority`, adds a non-panic unit test, and updates the changelog.
> 
> - **Ingester (reactive limiter)**:
>   - Pass the correct `prioritizer.Prioritizer` to `reactivelimiter.NewWithPriority` in `pkg/ingester/reactivelimiter.go` to avoid panic when push/read limiters with prioritization are enabled.
> - **Tests**:
>   - Add `pkg/ingester/reactivelimiter_test.go` ensuring constructing a prioritized reactive limiter doesn't panic.
> - **Changelog**:
>   - Add `[BUGFIX] Ingester: Panic when push and read reactive limiters are enabled with prioritization (#13482)`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit a0461a8307258eceb3b51aebd5a217aec026c8cd. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: pkg/ingester/reactivelimiter_test.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+func Test_ingesterReactiveLimiter(t *testing.T) {
+	t.Run("newReactiveLimiter with Prioritizer", func(t *testing.T) {
+		cfg := reactivelimiter.Config{}
+		cfg.Enabled = true
+		cfg.MaxLimitFactor = 1
+		cfg.InitialRejectionFactor = 1
+		cfg.MaxRejectionFactor = 2
+		prioritizer := reactivelimiter.NewPrioritizer(log.NewNopLogger())
+		newReactiveLimiter(&cfg, "read", log.NewNopLogger(), nil, priority.High, prioritizer)
```
Comment (56quarters) [inline pkg/ingester/reactivelimiter_test.go:23]: Maybe add a comment for this test explaining what it's testing? It's not obvious at first glance to me since there aren't any assertions.

**Comment by QuentinBisson** [comment]
Thanks for the fix :)
Do you know when this will be released?

**Comment by jhalterman** [comment]
> Do you know when this will be released?

I don't yet. For now I'd recommend just using either push or read reactive limiters.
