### PR TITLE
fix scheduler panic when serving dequeue request for disconnected querier-worker

### LINKED ISSUE #11337: Bug: Query-Scheduler - dequeueSelectNode : panic: runtime error: index out of range [-1]
### What is the bug?

We're investigating a problem detected on one of our Mimir clusters.
We observed a lot of errors from the queriers:

```
rpc error: code = Unknown desc = querier has informed the scheduler it is shutting down
```

Following this, we found that the query schedulers were frequently panicking when managing dequeueing:

```golang
panic: runtime error: index out of range [-1]
goroutine 31 [running]:
github.com/grafana/mimir/pkg/scheduler/queue/tree.(*QuerierWorkerQueuePriorityAlgo).dequeueSelectNode(0x47073d?, 0x7f77ee5f65b8?)
	/go/src/github.com/grafana/mimir/pkg/scheduler/queue/tree/tree_queue_algo_querier_worker_queue_priority.go:117 +0x5d
github.com/grafana/mimir/pkg/scheduler/queue/tree.(*Node).dequeue(0xc001d206c0)
	/go/src/github.com/grafana/mimir/pkg/scheduler/queue/tree/multi_algorithm_tree_queue.go:253 +0x107
github.com/grafana/mimir/pkg/scheduler/queue/tree.(*MultiAlgorithmTreeQueue).Dequeue(0xc0008ff0a0?, 0xc002b15220?)
	/go/src/github.com/grafana/mimir/pkg/scheduler/queue/tree/multi_algorithm_tree_queue.go:94 +0x33
github.com/grafana/mimir/pkg/scheduler/queue.(*queueBroker).dequeueRequestForQuerier(0xc001cdaa50, 0xc0026198c0)
	/go/src/github.com/grafana/mimir/pkg/scheduler/queue/queue_broker.go:137 +0xc3
github.com/grafana/mimir/pkg/scheduler/queue.(*RequestQueue).trySendNextRequestForQuerier(0xc000a38bb0, 0xc0026198c0)
	/go/src/github.com/grafana/mimir/pkg/scheduler/queue/queue.go:391 +0x3c
github.com/grafana/mimir/pkg/scheduler/queue.(*RequestQueue).dispatcherLoop(0xc000a38bb0)
	/go/src/github.com/grafana/mimir/pkg/scheduler/queue/queue.go:323 +0x62d
created by github.com/grafana/mimir/pkg/scheduler/queue.(*RequestQueue).starting in goroutine 29
	/go/src/github.com/grafana/mimir/pkg/scheduler/queue/queue.go:258 +0x4f
```

Related source code (git tag mimir2.15.2):
https://github.com/grafana/mimir/blob/mimir-2.15.2/pkg/scheduler/queue/tree/tree_queue_algo_querier_worker_queue_priority.go#L117

```golang
    currentNodeName := qa.nodeOrder[qa.currentNodeOrderIndex]
```

I'm trying to understand what's happening here and why we try to dequeue a out of range index, but I'm not sure exactly where to look. 

We cannot say for sure when it started due to log retention.

### How to reproduce it?

It happens frequently, we do not have a way to manually reproduce it.

### What did you think would happen?

No panic and restarting of query scheduler

### What was your environment?

Mimir 2.15.2 running on multiple instances 

### Any additional context to share?

Here is the configuration for both the scheduler and the querier.

Query scheduler config:

```yaml
query_scheduler:
    max_outstanding_requests_per_tenant: 100
    querier_forget_delay: 0s
    grpc_client_config:
        max_recv_msg_size: 209715200
        max_send_msg_size: 419430400
        grpc_compression: snappy
        rate_limit: 0
        rate_limit_burst: 0
        backoff_on_ratelimits: false
        backoff_config:
            min_period: 100ms
            max_period: 10s
            max_retries: 10
        initial_stream_window_size: 63KiB1023B
        initial_connection_window_size: 63KiB1023B
        tls_enabled: true
        tls_cert_path: /etc/ssl/ecdsa-ssl-cert-snakeoil.pem
        tls_key_path: /etc/ssl/ecdsa-ssl-key-snakeoil.pem
        tls_ca_path: /etc/ssl/ecdsa-ssl-cert-snakeoil.pem
        tls_server_name: ""
        tls_insecure_skip_verify: true
        tls_cipher_suites: ""
        tls_min_version: VersionTLS13
        connect_timeout: 5s
        connect_backoff_base_delay: 1s
        connect_backoff_max_delay: 5s
    service_discovery_mode: dns
    ring:
        kvstore:
            store: memberlist
            prefix: mimir/query_scheduler/
            consul:
                host: localhost:8500
                acl_token: '********'
                http_client_timeout: 20s
                consistent_reads: false
                watch_rate_limit: 1
                watch_burst_size: 1
                cas_retry_delay: 1s
            etcd:
                endpoints: []
                dial_timeout: 10s
                max_retries: 10
                tls_enabled: false
                tls_cert_path: ""
                tls_key_path: ""
                tls_ca_path: ""
                tls_server_name: ""
                tls_insecure_skip_verify: false
                tls_cipher_suites: ""
                tls_min_version: ""
                username: ""
                password: ""
            multi:
                primary: ""
                secondary: ""
                mirror_enabled: false
                mirror_timeout: 2s
        heartbeat_period: 15s
        heartbeat_timeout: 1m0s
        instance_id: *******
        instance_interface_names:
            - eth1
        instance_port: 0
        instance_addr: ""
        instance_enable_ipv6: false
    max_used_instances: 0
```
Querier config:
```yaml
querier:
    query_store_after: 23h45m0s
    store_gateway_client:
        tls_enabled: true
        tls_cert_path: /etc/ssl/ecdsa-ssl-cert-snakeoil.pem
        tls_key_path: /etc/ssl/ecdsa-ssl-key-snakeoil.pem
        tls_ca_path: /etc/ssl/ecdsa-ssl-cert-snakeoil.pem
        tls_server_name: ""
        tls_insecure_skip_verify: true
        tls_cipher_suites: ""
        tls_min_version: VersionTLS13
    shuffle_sharding_ingesters_enabled: true
    prefer_availability_zone: ""
    streaming_chunks_per_ingester_series_buffer_size: 256
    streaming_chunks_per_store_gateway_series_buffer_size: 256
    minimize_ingester_requests: true
    minimize_ingester_requests_hedging_delay: 3s
    query_engine: mimir
    enable_query_engine_fallback: true
    max_concurrent: 8
    timeout: 5m0s
    max_samples: 50000000
    default_evaluation_interval: 1m0s
    lookback_delta: 5m0s
    promql_experimental_functions_enabled: false
```
I can provide more logs if needed, as the problem happens frequently.

### PR DESCRIPTION
**Pull request by francoposa**
and reproduce with test

#### Which issue(s) this PR fixes or relates to

Fixes #11337 

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/scheduler/queue/queue_broker.go [hunk 1]
```diff
@@ -132,6 +132,11 @@ func (qb *queueBroker) dequeueRequestForQuerier(
 		return nil, nil, qb.tenantQuerierAssignments.queuingAlgorithm.TenantOrderIndex(), ErrQuerierShuttingDown
 	}
 
+	// check if the specific querier-worker connection was deregistered since its dequeue request was submitted
+	if dequeueReq.WorkerID == unregisteredWorkerID {
+		return nil, nil, qb.tenantQuerierAssignments.queuingAlgorithm.TenantOrderIndex(), ErrQuerierWorkerDisconnected
+	}
+
```
Comment (francoposa) [inline pkg/scheduler/queue/queue_broker.go:139]: this can be commented out to get the test to panic & reproduce the issue

File: pkg/scheduler/queue/queue_test.go [hunk 2]
```diff
@@ -329,6 +329,124 @@ func queueConsume(
...
+		Request:                   &httpgrpc.HTTPRequest{Method: "GET", Url: "/hello"},
+		AdditionalQueueDimensions: randAdditionalQueueDimension(""),
+	}
+	// The enqueuing of any new request triggers an attempt to dispatch requests
+	// to the items in waitingDequeueRequestsToDispatch list and their associated worker conns.
+	//
+	// The dequeue request at the front of that list will be associated with the disconnected worker conn,
+	// which now has a workerID set to unregisteredWorkerID = -1.
+	// Without any check in place to bail out before dequeuing for a workerID with -1,
+	// the QuerierWorkerQueuePriorityAlgo.dequeueSelectNode would panic with index out of range [-1].
```
Comment (chencs) [inline pkg/scheduler/queue/queue_test.go:416]:
```suggestion
	// Attempting to dequeue a request from the tree for an unregisteredWorkerID should fail, but not panic.
```

We don't have to explain the details of a panic that _shouldn't_ happen, we can link the bug report to this PR instead for posterity/documentation if someone wants to know.

**Review by chencs — APPROVED** [review]
Overall LGTM with some suggestions about wording; I think the test is a little confusing to read but I think it's because this edge case was confusing, and the comments do help a lot 🙂

File: pkg/scheduler/queue/queue.go [hunk 3]
```diff
@@ -337,7 +338,9 @@ func (q *RequestQueue) dispatcherLoop() {
 			for currentElement != nil {
 				waitingDequeueReq := currentElement.Value.(*QuerierWorkerDequeueRequest)
 				waitingDequeueReq.sendError(ErrStopped)
-				currentElement = currentElement.Next()
+				nextElement := currentElement.Next()
+				q.waitingDequeueRequestsToDispatch.Remove(currentElement)
+				currentElement = nextElement
```
Comment (francoposa) [inline pkg/scheduler/queue/queue.go:343]: @chencs So previously we didn't drop these elements from the queue after sending the "scheduler stopping error" to their receiver channel.
It did not affect anything, but dropping them makes it possible to assert on the desired outcome in our tests.

File: pkg/scheduler/queue/queue_test.go [hunk 4]
```diff
@@ -351,100 +351,96 @@ func TestDispatchToWaitingDequeueRequestForUnregisteredQuerierWorker(t *testing.
...
+		assert.True(t, errors.Is(err, ErrQuerierWorkerDisconnected) || errors.Is(err, context.Canceled) || errors.Is(err, ErrQuerierShuttingDown) || errors.Is(err, ErrStopped))
+	}
+
+	// Enqueue requests from a user which would NOT be sharded to querier-1.
 	// NOTE: "user-1" shuffle shard always chooses the first querier ("querier-1" in this case)
-	// when there are only one or two queriers in the sorted list of connected queriers
-	reqNotSharderToQuerier1 := &SchedulerRequest{
+	// when there are only one or two queriers in the sorted list of connected queriers.
+	//
+	// These will sit in the queue as user-1's sharded querier, querier-2 is not awaiting a request yet.
```
Comment (chencs) [inline pkg/scheduler/queue/queue_test.go:383]:
```suggestion
	// These will enqueue as querier-1's sharded query, querier-2 is not awaiting a request yet.
```
?

File: pkg/scheduler/queue/queue_test.go [hunk 5]
```diff
@@ -351,100 +351,96 @@ func TestDispatchToWaitingDequeueRequestForUnregisteredQuerierWorker(t *testing.
...
+	assertControlFlowError := func(t *testing.T, err error) {
+		// Error received by the querier connections waiting for a dequeue should be one of:
+		// * ErrQuerierWorkerDisconnected: the waiting conn was crashed or otherwise deregistered but the whole querier is not yet deregistered
+		// * context.Canceled: context cancellation also propagates on waiting conn crash/deregister and races with ErrQuerierWorkerDisconnected
+		// * ErrQuerierShuttingDown: querier has initiated shutdown or all conns deregistered
+		// * ErrStopped: The scheduler has received a shutdown signal and cleared its queue or lost all querier connections.
+		assert.True(t, errors.Is(err, ErrQuerierWorkerDisconnected) || errors.Is(err, context.Canceled) || errors.Is(err, ErrQuerierShuttingDown) || errors.Is(err, ErrStopped))
+	}
+
+	// Enqueue requests from a user which would NOT be sharded to querier-1.
```
Comment (chencs) [inline pkg/scheduler/queue/queue_test.go:379]:
```suggestion
	// Enqueue requests which will NOT be sharded to querier-1.
```

File: pkg/scheduler/queue/queue_test.go [hunk 6]
```diff
@@ -351,100 +351,96 @@ func TestDispatchToWaitingDequeueRequestForUnregisteredQuerierWorker(t *testing.
...
 	// NOTE: "user-1" shuffle shard always chooses the first querier ("querier-1" in this case)
-	// when there are only one or two queriers in the sorted list of connected queriers
-	reqNotSharderToQuerier1 := &SchedulerRequest{
+	// when there are only one or two queriers in the sorted list of connected queriers.
+	//
+	// These will sit in the queue as user-1's sharded querier, querier-2 is not awaiting a request yet.
+	// Two different additional queue dimensions must exist in the queue tree to create the potential panic condition.
```
Comment (chencs) [inline pkg/scheduler/queue/queue_test.go:384]:
```suggestion
	// >1 queue dimensions must exist in the queue to reproduce a potential panic condition (dims % unregisteredWorkerID)
```

File: pkg/scheduler/queue/queue_test.go [hunk 7]
```diff
@@ -351,100 +351,96 @@ func TestDispatchToWaitingDequeueRequestForUnregisteredQuerierWorker(t *testing.
 	// Two queriers connect, allowing us to enqueue requests sharded to only one of the two.
 	querier1Ctx, querier1CtxCancel := context.WithCancelCause(context.Background())
 	querier1Conn := NewUnregisteredQuerierWorkerConn(querier1Ctx, "querier-1")
-	require.NoError(t, queue.AwaitRegisterQuerierWorkerConn(querier1Conn))
+	assert.NoError(t, queue.AwaitRegisterQuerierWorkerConn(querier1Conn))
```
Comment (chencs) [inline pkg/scheduler/queue/queue_test.go:354]: Is there a reason you switched to `assert`s? Better to exit early if some of these fail, in my opinion.

File: pkg/scheduler/queue/queue_test.go [hunk 8]
```diff
@@ -351,100 +351,96 @@ func TestDispatchToWaitingDequeueRequestForUnregisteredQuerierWorker(t *testing.
...
-	//
-	// The dequeue request at the front of that list will be associated with the disconnected worker conn,
-	// which now has a workerID set to unregisteredWorkerID = -1.
-	// Without any check in place to bail out before dequeuing for a workerID with -1,
-	// the QuerierWorkerQueuePriorityAlgo.dequeueSelectNode would panic with index out of range [-1].
-	require.NoError(t, queue.SubmitRequestToEnqueue("user-2", reqNotSharderToQuerier1, 1, nil))
 
-	// The dequeue request should be dropped from the waiting list due to the error.
+	// Register another querier to trigger a re-shard and ensure we attempt to dispatch the requests.
+	// The queue will first try to dispatch a queue item to its internally-queued waiting dequeue requests.
```
Comment (chencs) [inline pkg/scheduler/queue/queue_test.go:428]:
```suggestion
	// Registering another querier triggers a re-shard, which triggers an attempt to dispatch waiting requests from the internal queue waitingDequeueRequestsToDispatch.
```

**Review by chencs — APPROVED** [review]
Looks good! This is an extensive enough test that I would add a short description before the test, even though the comments in the test are extensive. My suggestion (line breaks 🤷):

```
TestDispatchToWaitingDequeueRequestForUnregisteredQuerierWorker tests the scenario where a querier-worker submits a dequeue request while there are none to receive (i.e., no users sharded to that querier). 
The dequeue request is stored in an internal queue until a reshard or new enqueue request triggers dispatch of all waiting dequeue requests. 
If the querier-worker which originally submitted the dequeue request has since been unregistered (e.g., on querier crash but before forget delay), 
dispatch of the waiting dequeue request should fail gracefully.

File: pkg/scheduler/queue/queue_test.go (hunk 7 above)
Comment (francoposa) [reply pkg/scheduler/queue/queue_test.go:361]: From external conversation: asserts when I think I can find out more about why it failed if the tests continues.
Given the nondeterministic nature of message processing the `dispatcherLoop`, I have only the setup calls with `require` and everything else with `assert`.
