### PR TITLE
Fix find_prev_release() in tools/release/common.sh returns incorrect tag

### LINKED ISSUE #4824: find_prev_release() in tools/release/common.sh returns incorrect tag
#### Describe the bug
`find_prev_release()` in `tools/release/common.sh` sorts past tags by `taggerdate`. When backporting happens and the past minor version gets a patch, the logic in that bash function will return the incorrect previous release and therefore generate wrong diffs in the release note generated by `tools/release/create-draft-release.sh`.

#### To Reproduce
Given the following chronological tags (old tags first and newer tags later)

```
mimir-2.6.0-rc.0
mimir-2.6.0
mimir-2.7.0
mimir-2.7.1
mimir-2.8.0-rc.0
mimir-2.7.2
mimir-2.6.1
mimir-2.8.0-rc.1 # tag where we want to create a release
```

`tools/release/create-draft-release.sh` will incorrectly generate release with diff against `mimir-2.6.1` while it should generate release with diff against `mimir-2.8.0-rc.0`.

Given the following chronological tags (old tags first and newer tags later)

```
mimir-2.6.0-rc.0
mimir-2.6.0
mimir-2.7.0
mimir-2.7.1
mimir-2.8.0-rc.0
mimir-2.7.2
mimir-2.6.1
mimir-2.8.0-rc.1 
mimir-2.8.0 # tag where we want to create a release
```
`tools/release/create-draft-release.sh` will incorrectly generate release with diff against `mimir-2.6.1` while it should generate release with diff against `mimir-2.7.2`.

#### Expected behavior

`tools/release/create-draft-release.sh`  should generate release with diff against previous release ordered by tag (either stable or pre-release) instead of ordered by taggerdate.

#### Environment

Not relevant.

### PR DESCRIPTION
**Pull request by lamida**
#### Which issue(s) this PR fixes or relates to

Fixes #4824

* Get the last release using `git describe` (thanks to @pstibrany)
* Get previous release using some bash/sed-fu (thanks to @pracucci)

To test use this script in your local mimir repo. This script has some logic with the one in the PR. Please make sure to switch to release-xxx branch you want to test.

```bash
SED=$(which gsed || which sed)
# update last release version to test on correctly finding the previous release
LAST_RELEASE_VERSION="mimir-2.10.0-rc.2"
ALL_RELEASE_TAGS=$(git tag --list 'mimir-[0-9]*')
SORTED_RELEASE_TAGS=$(echo "$ALL_RELEASE_TAGS" | $SED '/rc/b; s/\(.*\)/\1-xx.x/' | sort --version-sort | gsed 's/-xx.x//')
if [[ $LAST_RELEASE_VERSION =~ "-rc" ]]; then
  PREV_RELEASE_TAG=$(echo "$SORTED_RELEASE_TAGS" | grep $(echo $LAST_RELEASE_VERSION) -B1 | head -1)
else 
  PREV_RELEASE_TAG=$(echo "$SORTED_RELEASE_TAGS" | grep -v -- '-rc' | grep $(echo $LAST_RELEASE_VERSION) -B1 | head -1) 
fi
echo $PREV_RELEASE_TAG
```

#### Checklist

- na Tests updated
- na Documentation added
- na `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: tools/release/common.sh [hunk 1]
```diff
@@ -44,9 +44,9 @@ find_prev_release() {
   find_last_release
```
Comment (krajorama) [inline tools/release/common.sh:44]: find_last_release also has `--sort=taggerdate` , which seems to be also wrong when we're doing parallel releases due to patching :(

**Comment by lamida** [comment]
I converted this back to draft to handle diff backport on previous minor release. I.e current minor version is 2.8.0. But when we release 2.7.3, the diff shouldn't be made ot 2.8.0 but instead to 2.7.2.

File: tools/release/common.sh [hunk 2]
```diff
@@ -44,9 +44,9 @@ find_prev_release() {
...
 
   if [[ $LAST_RELEASE_VERSION =~ "-rc" ]]; then
-    PREV_RELEASE_TAG=$(git tag --list --sort=taggerdate 'mimir-[0-9]*' | tail -2 | head -1)
```
Comment (pracucci) [inline tools/release/common.sh:47]: If we remove `--sort=taggerdate` the tags will be sorted lexicographically. I don't think it's correct, because it would break once we'll hit Mimir 2.10 in a couple of releases.

What we want here is getting the tags sorted by version. We could use `sort --version-sort` for that (e.g. `git tag --list 'mimir-[0-9]*' | sort --version-sort | tail -2 | head -1`) but the problem is that the release candidates wouldn't be sorted correctly.

For example, `git tag --list 'mimir-[0-9]*' | sort --version-sort` returns:

```
mimir-2.0.0
mimir-2.0.0-rc.0
mimir-2.0.0-rc.1
mimir-2.0.0-rc.2
mimir-2.0.0-rc.3
mimir-2.0.0-rc.4
mimir-2.1.0
mimir-2.1.0-rc.0
mimir-2.1.0-rc.1
mimir-2.2.0
mimir-2.2.0-rc.0
mimir-2.2.0-rc.1
mimir-2.3.0
mimir-2.3.0-rc0
mimir-2.3.0-rc.1
mimir-2.3.0-rc.2
mimir-2.3.1
mimir-2.4.0
mimir-2.4.0-rc.0
mimir-2.4.0-rc.1
mimir-2.5.0
mimir-2.5.0-rc.0
mimir-2.6.0
mimir-2.6.0-rc.0
mimir-2.6.1
mimir-2.7.0
mimir-2.7.1
mimir-2.7.2
mimir-2.8.0-rc.0
mimir-2.8.0-rc.1
mimir-2.8.0-rc.2
```

While what we want is:
```
mimir-2.0.0-rc.0
mimir-2.0.0-rc.1
mimir-2.0.0-rc.2
mimir-2.0.0-rc.3
mimir-2.0.0-rc.4
mimir-2.0.0
...
```

I've spent a good 30m playing with `sort` features, with no luck.

The hack I've found is to add a suffix which sort as last to each version not including "rc":

```
git tag --list 'mimir-[0-9]*' | gsed '/rc/b; s/\(.*\)/\1-xxx/' | sort --version-sort | gsed 's/-xxx//'
```

The output is:

```
mimir-2.0.0-rc.0
mimir-2.0.0-rc.1
mimir-2.0.0-rc.2
mimir-2.0.0-rc.3
mimir-2.0.0-rc.4
mimir-2.0.0
mimir-2.1.0-rc.0
mimir-2.1.0-rc.1
mimir-2.1.0
mimir-2.2.0-rc.0
mimir-2.2.0-rc.1
mimir-2.2.0
mimir-2.3.0-rc0
mimir-2.3.0-rc.1
mimir-2.3.0-rc.2
mimir-2.3.0
mimir-2.3.1
mimir-2.4.0-rc.0
mimir-2.4.0-rc.1
mimir-2.4.0
mimir-2.5.0-rc.0
mimir-2.5.0
mimir-2.6.0-rc.0
mimir-2.6.0
mimir-2.6.1
mimir-2.7.0
mimir-2.7.1
mimir-2.7.2
mimir-2.8.0-rc.0
mimir-2.8.0-rc.1
mimir-2.8.0-rc.2
```

NOTE: I've used `gsed` because OSX `sed` wouldn't work. If you adopt this approach, please use `$SED` and define it as `SED=$(which gsed || which sed)` (we already do it in `tools/release/create-draft-release-notes.sh` so we could just move it to `common.sh`.

**Comment by pstibrany** [comment]
I suggest to use `git describe --abbrev=0 --match 'mimir-[0-9]*'` to find previous tag on the same branch.

**Comment by pracucci** [comment]
@lamida Hi! I'm checking draft PRs. What's the state of this PR? Should we move forward or close it?

**Comment by lamida** [comment]
I forgot about this. We should move forward. I will do some more tests and have this merged.

File: tools/release/common.sh (hunk 1 above)
Comment (lamida) [reply tools/release/common.sh:49]: I will resolve this because this conversation is not relevant anymore.

File: tools/release/common.sh (hunk 2 above)
Comment (lamida) [reply tools/release/common.sh:47]: The change is applied as suggested.

File: tools/release/common.sh [hunk 3]
```diff
@@ -38,15 +42,21 @@ find_last_release() {
...
+# Previous release is one version before last release.
+# If last release is an rc, previous release can be any rc or non-rc.
+# If last release is a stable (non-rc) release, previous release must be a non-rc release.
 find_prev_release() {
   find_last_release
 
+  ALL_RELEASE_TAGS=$(git tag --list 'mimir-[0-9]*')
+
+  # To sort rc version correctly we use sed to append non-rc version with a temporary suffix
+  SORTED_RELEASE_TAGS=$(echo "$ALL_RELEASE_TAGS" | $SED '/rc/b; s/\(.*\)/\1-xx.x/' | sort --version-sort | gsed 's/-xx.x//')
```
Comment (charleskorn) [inline tools/release/common.sh:54]: Should this use `$SED` too?

```suggestion
  SORTED_RELEASE_TAGS=$(echo "$ALL_RELEASE_TAGS" | $SED '/rc/b; s/\(.*\)/\1-xx.x/' | sort --version-sort | $SED 's/-xx.x//')
```

Comment (krajorama) [reply tools/release/common.sh:54]: just tested the script, doesn't work on linux without this fix

**Review by krajorama — APPROVED** [review]
Did a little testing:

on main branch:
```
LAST_RELEASE_TAG=mimir-2.10.3
LAST_RELEASE_VERSION=2.10.3
PREV_RELEASE_TAG=mimir-2.10.2
PREV_RELEASE_VERSION=2.10.2
```

on release-2.10:
```
LAST_RELEASE_TAG=mimir-2.10.3
LAST_RELEASE_VERSION=2.10.3
PREV_RELEASE_TAG=mimir-2.10.2
PREV_RELEASE_VERSION=2.10.2
```

on release-2.9:
```
LAST_RELEASE_TAG=mimir-2.9.2
LAST_RELEASE_VERSION=2.9.2
PREV_RELEASE_TAG=mimir-2.9.1
PREV_RELEASE_VERSION=2.9.1
```

on release-2.8:
```
LAST_RELEASE_TAG=mimir-2.8.0
LAST_RELEASE_VERSION=2.8.0
PREV_RELEASE_TAG=mimir-2.7.3
PREV_RELEASE_VERSION=2.7.3
```

**Comment by lamida** [comment]
Thanks @krajorama. Test from RC branch also will work correctly. I merge this now.

File: tools/release/common.sh (hunk 3 above)
Comment (lamida) [reply tools/release/common.sh]: Thank you @charleskorn for catching that.
