### PR TITLE
fix: `TestIngester_inflightPushRequestsBytes` relax wait time & use a better condition verification

### LINKED ISSUE #11294: Flaky TestIngester_inflightPushRequestsBytes
```
--- FAIL: TestIngester_inflightPushRequestsBytes (6.54s)
    ingester_test.go:8791: 1 100000 69.868369ms
    ingester_test.go:8791: 1 2100000 1.422553747s
    ingester_test.go:8738: expected 1, got 0
    ingester_test.go:8766: 
                Error Trace:    /go/src/github.com/grafana/mimir/pkg/ingester/ingester_test.go:8766
                Error:          Received unexpected error:
                                 # HELP cortex_ingester_instance_rejected_requests_total Requests rejected for hitting per-instance limits
                                 # TYPE cortex_ingester_instance_rejected_requests_total counter
                                 cortex_ingester_instance_rejected_requests_total{reason="ingester_max_inflight_push_requests"} 0
                                -cortex_ingester_instance_rejected_requests_total{reason="ingester_max_inflight_push_requests_bytes"} 0
                                +cortex_ingester_instance_rejected_requests_total{reason="ingester_max_inflight_push_requests_bytes"} 3
                                 cortex_ingester_instance_rejected_requests_total{reason="ingester_max_inflight_read_requests"} 0
                                 cortex_ingester_instance_rejected_requests_total{reason="ingester_max_ingestion_rate"} 0
                                 cortex_ingester_instance_rejected_requests_total{reason="ingester_max_series"} 0
                                 cortex_ingester_instance_rejected_requests_total{reason="ingester_max_tenants"} 0
                                 
                Test:           TestIngester_inflightPushRequestsBytes
method=Ingester.Shipper.Sync level=info msg="uploading new block to long-term storage" block=00000000010000000000000000
method=Ingester.Shipper.Sync level=debug msg="uploaded file" from=/tmp/TestShipper_DeceivingUploadErrors1560796317/001/00000000010000000000000000/index dst=00000000010000000000000000/index bucket="fs: /tmp/TestShipper_DeceivingUploadErrors1560796317/002"
method=Ingester.Shipper.Sync level=error msg="uploading new block to long-term storage failed" block=00000000010000000000000000 err="failed to upload meta: base name matches, will fail upload"
```

### PR DESCRIPTION
**Pull request by rMaxiQp**
#### What this PR does

`inflightPushRequestsBytes` is updated after `inflightPushRequests` has been updated, and `inflightPushRequestsBytes` is required for later assertion. Thus, updating the assertion condition would help reduce the flakiness. In addition, since the request is meant to complete at least 1 second, we can relax a bit on the wait time to achieve a better success rate on overloaded machine.

#### Which issue(s) this PR fixes or relates to

Fixes #11294

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/ingester/ingester_test.go [hunk 1]
```diff
@@ -8851,9 +8851,9 @@ func TestIngester_inflightPushRequestsBytes(t *testing.T) {
 			// we can start the test.
 		}
 
-		test.Poll(t, targetRequestDuration/3, int64(1), func() interface{} {
-			return i.inflightPushRequests.Load()
-		})
+		require.Eventually(t, func() bool {
+			return i.inflightPushRequestsBytes.Load() > 0
```
Comment (aknuds1) [inline pkg/ingester/ingester_test.go]: Isn't it better to wait until `i.inflightPushRequestsBytes` equals `requestSize`, since that's what we assert on on line 8858? Otherwise there's a possible race I think, where `i.inflightPushRequestsBytes` is incremented, but not quite enough.
```suggestion
			return i.inflightPushRequestsBytes.Load() == int64(requestSize)
```

**Comment by rMaxiQp** [comment]
@aknuds1 Thank you for your review! The suggestion makes sense, and I've applied the change 🙇
