### PR TITLE
store-gateway: fix race in TestStreamBinaryReader_CheckSparseHeadersCorrectnessExtensive

### LINKED ISSUE #5943: Optimize TestStreamBinaryReader_CheckSparseHeadersCorrectnessExtensive
The test creates a single temporary directory and runs several test cases in parallel that create and test TSDB block.
This is likely wrong already, but it is very likely that due to https://github.com/prometheus/prometheus/pull/11818 it now became completely broken and nondeterministic.

 Discovered in #5927 .

Test should be made safe and optimal again.

### PR DESCRIPTION
**Pull request by dimitarvdimitrov**
This test was using multiple TSDB heads in the same directory, so compaction between each and writing chunks to files would sometimes collide.

Fixes #5943

### CODE REVIEW

**Review by krajorama — APPROVED** [review]

File: pkg/storegateway/indexheader/stream_binary_reader_test.go [hunk 1]
```diff
@@ -99,6 +94,11 @@ func TestStreamBinaryReader_CheckSparseHeadersCorrectnessExtensive(t *testing.T)
 
 			t.Run(fmt.Sprintf("%vNames%vValues", nameCount, valueCount), func(t *testing.T) {
 				t.Parallel()
+				tmpDir := t.TempDir()
+				bkt, err := filesystem.NewBucket(filepath.Join(tmpDir, "bkt"))
+
```
Comment (dimitarvdimitrov) [inline pkg/storegateway/indexheader/stream_binary_reader_test.go:99]:
```suggestion
```
