### PR TITLE
Fix web UI links not respecting path-prefix configuration

### LINKED ISSUE #13476: -server.path-prefix / server.http_path_prefix breaks static assets and redirects
### What is the bug?

Hello,
the problem is that when using either
-server.path-prefix=/mimir (CLI) or server.http_path_prefix: /mimir (YAML),
the prefix works for API routes but breaks the web UI.

When the prefix is enabled:

All static assets (CSS, JS, images) return 404 Not Found.

The web interface loads as unstyled HTML (no CSS/icons).

The “Current config (diff)” link points to /config (missing the prefix) and also returns 404.

Example errors from Chrome DevTools (direct node access, no proxy):

```
GET https://<host>:8080/mimir/static/mimir-styles.css → 404
GET https://<host>:8080/config → 404
```

### How to reproduce it?

How to reproduce it?

Start Grafana Mimir 3.0.0:

```
docker run -d \
  -p 9009:9009 \
  grafana/mimir:3.0.0 \
  -server.path-prefix=/mimir
```

Open http://localhost:9009/mimir/ in a browser.

Observe that the UI loads without CSS or images and browser console shows 404s for /mimir/static/....

Click on Current config (diff) — it redirects to /config (missing /mimir/) and returns 404.

### What did you think would happen?

All API routes and static assets should respect the configured path prefix.
The UI should load correctly with all styles and images available, and internal links (like /config) should include the prefix (/mimir/config).

also all pictures and css files.

### What was your environment?

- Mimir version: 3.0.0 (revision 3e9aeb43)
- Deployment: Docker on bare metal
- Mode: Monolithic (target: all)
- Browser: Chrome (latest)
- Configuration tested:
```
YAML: server.http_path_prefix: /mimir
CLI: -server.path-prefix=/mimir
```

When server.http_path_prefix is empty (default), the UI and assets work normally.

### Any additional context to share?

everything is working normaly when the http prefix isnt set!

Image

### PR DESCRIPTION
**Pull request by ElsaDevOps**
#### What this PR does

Fixes web UI links (like `/config`, `/alertmanager`, etc.) not respecting the `-server.path-prefix` configuration. When path prefix is set to `/mimir`, internal links now correctly point to `/mimir/config` instead of `/config`.

The fix adds a resolveBaseURL helper function registered with templates. Templates now handle URL construction directly via {{ resolveBaseURL $.BaseURL .Path }}, which allows all template-built links (including links to related pages) to respect the path prefix.

#### Which issue(s) this PR fixes or relates to

Partially fixes #13476. This addresses hardcoded absolute paths in UI links. Static asset 404s may be a separate issue.

#### Checklist

- [x] Tests updated.
- [ ] Documentation added. *(not needed, existing flag, bugfix only)*
- [x] `CHANGELOG.md` updated
- [ ] `about-versioning.md` updated with experimental features. *(not needed, not an experimental feature)*

---

> [!NOTE]
> Fixes admin UI links so they correctly include the configured base path.
> 
> - Pass `serverCfg.PathPrefix` into `IndexPageContent` and expose as `BaseURL`
> - Add `resolveBaseURL` helper and register it in template funcs; use it in `index.gohtml` for all link hrefs
> - Adjust template loop vars and data passed to template; update tests and add unit test for URL resolution
> - Update `CHANGELOG.md` with the bugfix entry
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 601ba68b963f46a9867d93b35b2911faad272935. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: pkg/api/handlers.go [hunk 1]
```diff
@@ -77,6 +79,12 @@ func (pc *IndexPageContent) AddLinks(weight int, groupDesc string, links []Index
 	pc.mu.Lock()
 	defer pc.mu.Unlock()
 
+	for i := range links {
+		if strings.HasPrefix(links[i].Path, "/") {
+			links[i].Path = pc.PathPrefix + links[i].Path
+		}
+	}
```
Comment (narqo) [inline pkg/api/handlers.go]: Rather than building the URLs in-place, what if we pass the `PathPrefix` with the template's data, and resolve the links in the template? That is, we update the type `indexPageContents` to hold `BaseURL string`, and populate it when we build the template in the handler.

The motivation for this is that inside different templates Mimir UI, sometimes, builds links to related pages. E.g. the `/compactor/tenant/<tenant>/planned_jobs` has a link to compactor's ring. I think it would more consistent if we made it a habit, that a template must have the correct `BaseURL` in its context, and that it's the template's responsibility to produce a working link.

What do you think?

Comment (ElsaDevOps) [reply pkg/api/handlers.go]: I agree and I see what you're saying about having the template handle this logic. I will revise the PR to have the template do this. Is there anything else you think I should consider?

File: pkg/api/handlers.go [hunk 2]
```diff
@@ -112,17 +114,27 @@ var indexPageHTML string
...
+	if strings.HasPrefix(path, "/") {
+		return strings.TrimSuffix(baseURL, "/") + path
+	}
+	return path
+}
+
 func indexHandler(content *IndexPageContent) http.HandlerFunc {
-	templ := template.New("main")
+	templ := template.New("main").Funcs(template.FuncMap{
+		"prependBaseURL": prependBaseURL,
```
Comment (narqo) [inline pkg/api/handlers.go]: (nit) Could we call it "resolve"

```suggestion
		"resolveBaseURL": resolveBaseURL,
```

Comment (ElsaDevOps) [reply pkg/api/handlers.go]: Yeah of course, I'll update that now.

File: CHANGELOG.md [hunk 3]
```diff
@@ -3,7 +3,7 @@
 ## main / unreleased
 
 ### Grafana Mimir
-
+* [BUGFIX] API: Fixed web UI links not respecting `-server.path-prefix` configuration. #14090
```
Comment (narqo) [inline CHANGELOG.md]: Could you put the "BUGFIX" line down into the changelog, close to the rest of bugfixes. This will make it simpler, to whoever reads the changelog, to focus on potentially large changes and enhancements, vs. the rest of the bugfixes in the release.

Comment (ElsaDevOps) [reply CHANGELOG.md]: Okay, I've put my changelog entry on top of the other recent BUGFIX entries.

**Comment by ElsaDevOps** [comment]
> Works for me, thank you 🔥 
> 
> 
> 
> JFI, I've rebased the branch to resolve a merge conflict.

I'm glad that I was able to help, and thank you very much for your help and guidance too!
