### PR TITLE
Use BasicLifecycler for distributors and auto-forget

### LINKED ISSUE #2138: Migrate distributors hash ring to BasicLifecycler and add auto-forget feature
When a distributor crash and is restarted with a different instance ID, it will never leave the hash ring and the instance will be in the hash ring with "Unhealthy" state until an human operator will manually forget through the admin UI. The "Unhealthy" distributor in the ring does **not cause any issue** in the Mimir cluster, but it's misleading for users and we should fix it.

The distributors hash ring is still implemented using the old `ring.Lifecycler`:
https://github.com/grafana/mimir/blob/e11ac855ba074308735271208931c20bc2ce0445/pkg/distributor/distributor.go#L220

We should:
1. Migrate the distributor hash ring to [`ring.BasicLifecycler`](https://github.com/grafana/dskit/blob/ebb5c6de233d26951aef41eada3cab3295ecb368/ring/basic_lifecycler.go#L89)
2. Enable the [auto-forget feature](https://github.com/grafana/dskit/blob/ebb5c6de233d26951aef41eada3cab3295ecb368/ring/basic_lifecycler_delegates.go#L121)

### PR DESCRIPTION
**Pull request by 56quarters**
#### What this PR does

Use the BasicLifecycler in distributors for managing their lifecycle so
that we can take advantage of the "auto-forget" delegates feature. This
prevents the ring from filling up with "unhealthy" distributors that are
never removed. This wasn't a bug but it was confusing for users and
operators.

#### Which issue(s) this PR fixes or relates to

Fixes #2138

Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>

#### Checklist

- [X] Tests updated
- [na] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/distributor/distributor.go [hunk 1]
```diff
@@ -322,8 +300,9 @@ func New(cfg Config, clientConfig ingester_client.Config, limits *validation.Ove
 			Help:      "The configured replication factor.",
 		}),
 		latestSeenSampleTimestampPerUser: promauto.With(reg).NewGaugeVec(prometheus.GaugeOpts{
-			Name: "cortex_distributor_latest_seen_sample_timestamp_seconds",
-			Help: "Unix timestamp of latest received sample per user.",
+			Namespace: "cortex",
+			Name:      "distributor_latest_seen_sample_timestamp_seconds",
```
Comment (pstibrany) [inline pkg/distributor/distributor.go:304]: Nit: please don't introduce using `Namespace`, but use `Name` only. It makes it easier to find the metric name in the codebase.

Comment (56quarters) [reply pkg/distributor/distributor.go:304]: OK. I was updating this one because the rest of the metrics in the file are `Namespace` + `Name` style. Do you think I should update them all to use `Name` only? Or just revert this instance?

File: pkg/distributor/distributor_ring.go [hunk 2]
```diff
@@ -16,8 +16,13 @@ import (
...
 	"github.com/grafana/dskit/netutil"
 	"github.com/grafana/dskit/ring"
+)
 
-	util_log "github.com/grafana/mimir/pkg/util/log"
+const (
+	// ringNumTokens is how many tokens each distributor should have in the ring.
+	// Distributors use a ring because they need to know how many distributors there
+	// are in total for rate limiting.
+	ringNumTokens = 1
```
Comment (colega) [inline pkg/distributor/distributor_ring.go:25]: Even though we use the ring just to know the number of instances, I'd still set this to a sane value, as someone may use the ring for something _decent_ in the future and can oversee this detail.

```suggestion
	ringNumTokens = 128
```

Comment (pstibrany) [reply pkg/distributor/distributor_ring.go:25]: More tokens make the ring bigger, it means more memory usage, larger CAS operations (consul) or bigger gossiped messages (memberlist). We use 1 token in this ring for ages (2 years) now. I'd keep it as it until we actually need more tokens.

Comment (colega) [reply pkg/distributor/distributor_ring.go:25]: Well, if this isn't new, then ok!

File: pkg/distributor/distributor.go [hunk 3]
```diff
@@ -351,7 +329,46 @@ func New(cfg Config, clientConfig ingester_client.Config, limits *validation.Ove
 		return d.ingestionRate.Rate()
 	})
 
-	d.forwarder = forwarding.NewForwarder(reg, d.cfg.Forwarding)
+	// Create the configured ingestion rate limit strategy (local or global). In case
+	// it's an internal dependency and can't join the distributors ring, we skip rate
+	// limiting.
+	var ingestionRateStrategy, requestRateStrategy limiter.RateLimiterStrategy
+	var distributorsLifeCycler *ring.BasicLifecycler
```
Comment (colega) [inline pkg/distributor/distributor.go:336]: Nit: can we use `Lifecycler` as single word (instead of `LifeCycler`) everywhere? Just for consistency with its spelling in `ring`

File: pkg/distributor/distributor.go [hunk 4]
```diff
@@ -351,7 +329,46 @@ func New(cfg Config, clientConfig ingester_client.Config, limits *validation.Ove
 		return d.ingestionRate.Rate()
 	})
 
-	d.forwarder = forwarding.NewForwarder(reg, d.cfg.Forwarding)
+	// Create the configured ingestion rate limit strategy (local or global). In case
+	// it's an internal dependency and can't join the distributors ring, we skip rate
```
Comment (pstibrany) [inline pkg/distributor/distributor.go:333]: :question: ... and WE can't ...

File: pkg/distributor/distributor.go [hunk 5]
```diff
@@ -351,7 +329,46 @@ func New(cfg Config, clientConfig ingester_client.Config, limits *validation.Ove
...
+	if !canJoinDistributorsRing {
+		requestRateStrategy = newInfiniteRateStrategy()
+		ingestionRateStrategy = newInfiniteRateStrategy()
+	} else {
+		kvStore, err := kv.NewClient(cfg.DistributorRing.KVStore, ring.GetCodec(), kv.RegistererWithKVName(reg, "distributor-lifecycler"), log)
+		if err != nil {
+			return nil, errors.Wrap(err, "failed to initialize distributors' KV store")
+		}
+
+		delegate := ring.BasicLifecyclerDelegate(ring.NewInstanceRegisterDelegate(ring.ACTIVE, ringNumTokens))
```
Comment (pstibrany) [inline pkg/distributor/distributor.go:348]: Nit: Here we use casting to change type of `delegate`. Let's be explicit about it:

```suggestion
		var delegate ring.BasicLifecyclerDelegate
		delegate = ring.NewInstanceRegisterDelegate(ring.ACTIVE, ringNumTokens)
```

File: pkg/distributor/instance_count.go [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+
+// OnRingInstanceHeartbeat implements the ring.BasicLifecyclerDelegate interface
+func (d *healthyInstanceDelegate) OnRingInstanceHeartbeat(lifecycler *ring.BasicLifecycler, ringDesc *ring.Desc, instanceDesc *ring.InstanceDesc) {
+	activeMembers := uint32(0)
+
+	for _, instance := range ringDesc.Ingesters {
+		if ring.ACTIVE == instance.State {
+			activeMembers++
+		}
+	}
```
Comment (pstibrany) [inline pkg/distributor/instance_count.go:45]: We also need to check if instance has heartbeated recently, otherwise it can be an old entry in the ring, left after crashed distributor (`instance.IsHeartbeatHealthy()`).

File: pkg/distributor/distributor_ring.go [hunk 7]
```diff
@@ -61,39 +66,16 @@ func (cfg *RingConfig) RegisterFlags(f *flag.FlagSet, logger log.Logger) {
...
+	return ring.BasicLifecyclerConfig{
+		ID:                              cfg.InstanceID,
+		Addr:                            cfg.InstanceAddr,
+		HeartbeatPeriod:                 cfg.HeartbeatPeriod,
+		HeartbeatTimeout:                cfg.HeartbeatTimeout,
+		TokensObservePeriod:             0,
+		NumTokens:                       ringNumTokens,
+		KeepInstanceInTheRingOnShutdown: false,
+	}
 }
```
Comment (pstibrany) [inline pkg/distributor/distributor_ring.go:80]: Please take a look at `ToLifecyclerConfig` in `gateway_ring.go` ([link](https://github.com/grafana/mimir/blob/98df41bee65ec377746e09018f19543d5a00e9eb/pkg/storegateway/gateway_ring.go#L144)) for an example how to properly use Interface names and instance port.

File: pkg/distributor/distributor.go (hunk 4 above)
Comment (56quarters) [reply pkg/distributor/distributor.go:333]: Oops. Must have gotten lost during a refactor.

**Review by colega — APPROVED** [review]

**Review by pstibrany — APPROVED** [review]
Thank you! Nice work.

File: pkg/distributor/instance_count_test.go [hunk 8]
```diff
@@ -0,0 +1,136 @@
...
+			},
+			heartbeatTimeout: time.Minute,
+			expectedCount:    3,
+		},
+
+		"all instances healthy not all instances active": {
+			ringSetup: func(desc *ring.Desc) ring.InstanceDesc {
+				now := time.Now()
+
+				instance1 := desc.AddIngester("distributor-1", "127.0.0.1", "", []uint32{1}, ring.ACTIVE, now)
```
Comment (pstibrany) [inline pkg/distributor/instance_count_test.go:61]: what about having `addInstance(desc, id, state, timestamp)` helper function inside this test?

Comment (56quarters) [reply pkg/distributor/instance_count_test.go:61]: good idea

File: pkg/distributor/distributor.go [hunk 9]
```diff
@@ -65,8 +66,12 @@ var (
...
 
 const (
-	// DistributorRingKey is the key under which we store the distributors ring in the KVStore.
-	DistributorRingKey = "distributor"
+	// distributorRingKey is the key under which we store the distributors ring in the KVStore.
+	distributorRingKey = "distributor"
+
+	// ringAutoForgetUnhealthyPeriods is how many consecutive timeout periods an unhealthy instance
+	// in the ring will be automatically removed after.
+	ringAutoForgetUnhealthyPeriods = 10
```
Comment (pracucci) [inline pkg/distributor/distributor.go:74]: Looks very high. I would be more aggressive with distributors, like 2 or 3 should be more than enough.
