### PR TITLE
Query all ingesters when shuffle sharding is disabled

### LINKED ISSUE #10531: Bug: Shuffle sharding is not working as desired for ingesters
### What is the bug?

Hi Team,

We are currently on Grafana 2.14.3, and we were trying to decrease the tenant shard size by following these [steps](https://grafana.com/docs/mimir/latest/configure/configure-shuffle-sharding/#limitation-decreasing-the-tenant-shard-size) in runbook.

We noticed discrepancy in number of metrics as soon as we try to reduce tenant shard size for a tenant after disabling shuffle sharding (`-querier.shuffle-sharding-ingesters-enabled=false`). This flag was modified under [querier block](https://grafana.com/docs/mimir/latest/configure/configuration-parameters/#querier) and was verified by sshing in the queriers pod.

Shuffle sharding is not working as desired.

### How to reproduce it?

1. Start Grafana 2.14.3
2. Disable shuffle sharding so that querier can query all ingesters
3. After reducing tenant shard size of a certain tenant we saw reduction in number of metrics (`count({__name__=~".+"})`) at given point of time.  Attaching screenshots for before/after modifying shard size. Shard size was modified from 41 to 16 for tenant.

### What did you think would happen?

For a given point of time, no of metrics count shouldn't change as querier should be able to query all ingesters.

### What was your environment?

Kubernetes

### Any additional context to share?

Image
Image

### PR DESCRIPTION
**Pull request by jhalterman**
When shuffle sharding is disabled, we should still query all ingesters, regardless of read only mode. The current behavior may filter out ingesters that are in read only mode for queries, when shuffle sharding is enabled, which is not desired. 

This PR reverts to the prior behavior, which was removed in https://github.com/grafana/mimir/pull/8956, for deciding when to create a shuffle shard with lookback.

#### Which issue(s) this PR fixes or relates to

Fixes #10531

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

---

> [!NOTE]
> Restores querying all ingesters when shuffle sharding is disabled.
> 
> - In `pkg/distributor/query.go`, apply `ShuffleShardWithLookback` only if `ShuffleShardingLookbackPeriod > 0`; otherwise use the full ingesters ring
> - Extend `query_test.go` to cover the disabled-shuffle-sharding case (new flag in test data and config hook) and validate ingester selection
> - Add `[BUGFIX]` entry to `CHANGELOG.md` documenting the ingester selection behavior
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 25c211203b226885ad86b1e4ee4e48304a19a12f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: pkg/distributor/query.go [hunk 1]
```diff
@@ -137,7 +137,11 @@ func (d *Distributor) getIngesterReplicationSetsForQuery(ctx context.Context) ([
 	// Lookup ingesters ring because ingest storage is disabled.
 	shardSize := d.limits.IngestionTenantShardSize(userID)
 	r := d.ingestersRing
-	r = r.ShuffleShardWithLookback(userID, shardSize, d.cfg.ShuffleShardingLookbackPeriod, time.Now())
+
+	// If tenant uses shuffle sharding, we should only query ingesters which are part of the tenant's subring.
+	if lookbackPeriod := d.cfg.ShuffleShardingLookbackPeriod; shardSize > 0 && lookbackPeriod > 0 {
```
Comment (charleskorn) [inline pkg/distributor/query.go]: If the lookback period is 0, won't we always query all ingesters, even if shuffle sharding is enabled?

**Review by charleskorn — COMMENTED** [review]
Could you please add some tests for this?

File: pkg/distributor/query.go (hunk 1 above)
Comment (jhalterman) [reply pkg/distributor/query.go]: Yep - that's intended. This change reverts the removal of this condition during a previous PR when read only mode was added, and brings the behavior with classic storage inline with using ingest storage (above).

Comment (charleskorn) [reply pkg/distributor/query.go]: But if shuffle sharding is enabled, don't we want to query just the tenant's shard?

Comment (charleskorn) [reply pkg/distributor/query.go]: (or: why are we using the lookback period to decide if shuffle sharding is enabled or not, rather than the shard size?)

Comment (jhalterman) [reply pkg/distributor/query.go]: > why are we using the lookback period to decide if shuffle sharding is enabled or not

I'm not sure why that setting was used for this purpose, perhaps because shuffle sharding with lookback was meant to be called only with a non-zero lookback, but it goes back to the [origin of this feature](https://github.com/grafana/mimir/commit/ff9c2a3290f7a355df3624d18bac4f9c7309f52c#diff-c5d6cd57cfca24952cce86aa3dd9bff51046629b3156060853fcfdfb896b590eR90) and is still used for this purpose with ingest storage. This PR reverts to that prior behavior since it also resolves the problem we're interested in - querying read only ingesters when shuffle sharding is disabled.

**Comment by duricanikolic** [comment]
@jhalterman for completeness, could you also mention the PR that introduced the bug in this PR’s description?

File: pkg/distributor/query.go (hunk 1 above)
Comment (pracucci) [inline pkg/distributor/query.go]: Why was this check removed in https://github.com/grafana/mimir/pull/8956? I think it was related to the read only state. We implemented the filtering of read only ingesters only in the shuffle sharding ring functions, so I'm wondering if – by doing this change – we're going to break read only under some conditions. @pr00se may also remember the rationale behind the original change.

Comment (pracucci) [reply pkg/distributor/query.go]: > But if shuffle sharding is enabled, don't we want to query just the tenant's shard?

I don't think there's a real use case for querying only the current shard without lookback, because it would open to consistency bugs in case there was a scaling operation in the last 13h. For this reason, in the past we've used `ShuffleShardingLookbackPeriod=0` to signal "shuffle sharding disabled" in the config, but I do understand it's a very obscure way to do it.

I'm happy to review a change that makes the "shuffle sharding enabled/disabled" much more explicit.

Comment (jhalterman) [reply pkg/distributor/query.go]: It may have been intended to allow read only filtering to always happen, which is the bug, since we don't want to do that filtering for reads.

Comment (pracucci) [reply pkg/distributor/query.go]: If the shard size is 0 (shuffle sharding disabled) we still need to filter out read-only instances that have changed state longer than lookbackPeriod ago. This filter is done inside ShuffleShardWithLookback() (I know, it's obscure that do read-only instances filtering there, but that's how we ended up).

I think this is the reason why the `if` condition was removed https://github.com/grafana/mimir/pull/8956 and I think that your proposed change in this PR is still not correct.

Now the question is, what if we do add `if lookbackPeriod > 0` only? That's the question I struggle the most to reason about. Theoretically it should be fine, but I'm wondering if we may hit edge cases when the read-only instance is about to be terminated because more than the expected in read-only state has passed. In that case, I think we may end up in a situation where the querier computes the replication state including a ingester that is about to be terminated, and the query fails because the ingester gets terminated in the meanwhile. Today this situation shouldn't happen because we always call `ShuffleShardWithLookback()` (that filters out read-only instances that have been in that state since longer than lookbackPeriod) even if shuffle sharding is disabled (shardSize is 0) and lookbackPeriod is always valued.

Comment (pracucci) [reply pkg/distributor/query.go]: > If the shard size is 0 (shuffle sharding disabled) we still need to filter out read-only instances that have changed state longer than lookbackPeriod ago

In this context, lookbackPeriod is the time we need to query an ingester – after it stopped receiving new samples – to guarantee query consistency.

Comment (pracucci) [reply pkg/distributor/query.go]: Maybe we can ignore the edge case and simply have `if lookbackPeriod > 0` (but with a code comment explaining "why") but I think that `ShuffleShardWithLookback()` should be called even when `shardSize == 0`, reason why I'm not convinced your change is correct.

Comment (jhalterman) [reply pkg/distributor/query.go]: > we still need to filter out read-only instances that have changed state longer than lookbackPeriod ago.

That's what `Ring.ShuffleShardWithLookback` documents as its behavior, but it doesn't seem incorrect to query read only instances, just inefficient.

> I'm wondering if we may hit edge cases when the read-only instance is about to be terminated because more than the expected in read-only state has passed

Possibly, but if an instance is not healthy it should already be filtered from the ReplicationSet, regardless of the lookback period. Using the lookback period as a filter for read-only instances that might be about to leave seems inappropriate.

> what if we do add if lookbackPeriod > 0 only?

That would resolve the inefficiency. Walking through a few use cases:

- shardSize=0, lookback=0: no shuffle shard, this is expected
- shardSize=0, lookback=12h: read only instances filtered, which matches the documented `Ring.ShuffleShardWithLookback` behavior
- shardSize=3, lookback=0: no shuffle shard, which is expected as @pracucci described above
- shardSize=3, lookback=12h: shuffle shard with read only instances filtered

So, I think your suggestion is an improvement. Let me know if you're in agreement, and if so, if we'd want to change for ingest storage as well (maybe separately).

**Review by pracucci — APPROVED** [review]
Thanks!
