### PR TITLE
Maybe fix TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged flakyness

### LINKED ISSUE #5244: Flaky TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged
The `TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged` test looks flaky ([logs](https://github.com/grafana/mimir/actions/runs/5264357324/jobs/9515545279?pr=5122)):

```
--- FAIL: TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged (0.63s)
    ruler_test.go:1254: 
        	Error Trace:	/__w/mimir/mimir/pkg/ruler/ruler_test.go:1254
        	Error:      	Not equal: 
        	            	expected: []int{100}
        	            	actual  : []int{71, 100}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,3 @@
        	            	-([]int) (len=1) {
        	            	+([]int) (len=2) {
        	            	+ (int) 71,
        	            	  (int) 100
        	Test:       	TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged
```

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does
I looked into #5244 and I'm not 💯 sure why `TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged` failed in CI. I haven't been able to reproduce it locally, not even adding few random sleeps here and there (I suspect a timing issue). The CI logs didn't help much because I can't distinguish logs between the 2 ruler instances in the test, so in this PR:

1. Use `test.Poll()` for `getLocalRules()` assertions
2. Add the instance ID as log field, so that we can better distinguish logs between ruler instances

#### Which issue(s) this PR fixes or relates to

Maybe fixes #5244

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by flxbk — APPROVED** [review]
Thank you! 🤞

File: pkg/ruler/ruler_test.go [hunk 1]
```diff
@@ -1211,14 +1213,17 @@ func TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleT
...
 	// We expect rule groups to have been sharded between the rulers.
-	actualRuleGroupsCount := 0
-	for _, ruler := range rulers {
-		actualRuleGroups, err := ruler.getLocalRules(userID, AnyRule)
-		require.NoError(t, err)
-		require.NotEmpty(t, actualRuleGroups)
-		actualRuleGroupsCount += len(actualRuleGroups)
-	}
-	assert.Equal(t, numRuleGroups, actualRuleGroupsCount)
+	test.Poll(t, time.Second, numRuleGroups, func() interface{} {
```
Comment (krajorama) [inline pkg/ruler/ruler_test.go:1216]: I don't think this checks sharding because require.NotEmpty(t, actualRuleGroups)  is not replaced with anything. This it can succeed even if only one ruler has all groups.

Comment (pracucci) [reply pkg/ruler/ruler_test.go]: Good point! I slightly modified the suggestion to return a value which would be easier to debug in case of assertion failures: https://github.com/grafana/mimir/pull/5250/commits/59c0f0954c41a42379ceb1ab0a21c7c9df219975

**Review by krajorama — APPROVED** [review]
LGTM
