### PR TITLE
Fixes flaky TestSchedulerShutdown_QuerierLoop

### LINKED ISSUE #14077: Flaky TestSchedulerShutdown_QuerierLoop
## `TestSchedulerShutdown_QuerierLoop`

`pkg/scheduler/scheduler_test.go`

### About This Issue
This issue tracks a flaky test that has been detected failing inconsistently. Each week our analysis tool runs and detects this test as flaky, it will add a comment below with recent failure data and who might be able to help.

### 🔍 How to investigate
1. **Run it locally** to see if you can reproduce: `go test -count=10000 -run TestSchedulerShutdown_QuerierLoop ./...`
2. **Check the failure logs** in the comments below - they might show a pattern
3. **Look for timing issues** - race conditions, timeouts, or external dependencies
4. **Review recent changes** - check commits that modified this test or the code under test recently

### 🎯 Next steps
- **Can you fix it?** Great! That would help the whole team
- **Need help?** Ask someone who has worked on this area recently
- **Can't fix it right now?** Consider adding logs and metrics so that next time it's easier to debug.
- **Obsolete test?** Maybe it's time to remove it or skip it with `t.Skip()`

_This test has been identified as flaky by [go-flaky-tests](https://github.com/grafana/shared-workflows/tree/main/actions/go-flaky-tests)._

### PR DESCRIPTION
**Pull request by monoxane**
This PR fixes an occasional TestSchedulerShutdown_QuerierLoop failure where the scheduler completely terminates before the test querier sends its polling/unblock request (intentional) and the gRPC connection returns an io.EOF error (not originally handled).

#### Which issue(s) this PR fixes or relates to
Fixes #14077

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

---

> [!NOTE]
> Improves reliability of scheduler shutdown tests and clarifies expected cancellation behavior.
> 
> - Introduces shared `drainingCancellationError` and uses it in `drainScheduler()`
> - Updates `TestSchedulerShutdown_QuerierLoop` to handle `io.EOF` when the scheduler exits and to assert the cancelled dequeue via `grpcutil.ErrorToStatus` matching `drainingCancellationError`
> - Adds `grpcutil` import in tests
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 47e79e47d9c0c5a2727a1ac473200e9a9764ced5. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by tcp13equals2 — APPROVED** [review]

File: pkg/scheduler/scheduler_test.go [hunk 1]
```diff
@@ -493,6 +493,12 @@ func TestSchedulerShutdown_QuerierLoop(t *testing.T) {
 
 	// Unblock scheduler loop, to find next request.
 	err = querierLoop.Send(&schedulerpb.QuerierToScheduler{})
```
Comment (charleskorn) [inline pkg/scheduler/scheduler_test.go:497]: If a gRPC stream returns `io.EOF` from `Send`, then the true error can be read by calling `Recv` - so it might be worth checking what `Recv` returns here.

[The docs](https://github.com/grpc/grpc-go/blob/bd4444a0a2fdd66245f9e0f0d140aafb5b49044c/stream.go#L115-L120) for `ClientStream` explain this further (the generated `Send` and `Recv`  methods internally call `ClientStream.SendMsg` and `ClientStream.RecvMsg`, respectively).

File: pkg/scheduler/scheduler_test.go [hunk 2]
```diff
@@ -491,11 +491,13 @@ func TestSchedulerShutdown_QuerierLoop(t *testing.T) {
...
-	require.NoError(t, err)
+	if err != nil {
+		require.ErrorIs(t, io.EOF, err)
+	}
 
-	// This should now return with error, since scheduler is going down.
+	// This should return with error, since scheduler has terminated.
 	_, err = querierLoop.Recv()
 	require.Error(t, err)
```
Comment (charleskorn) [inline pkg/scheduler/scheduler_test.go]: [nit] Can we make a stronger assertion about the error returned, to ensure it failed for the expected reason?

Comment (monoxane) [reply pkg/scheduler/scheduler_test.go]: I don't actually know if it's possible to match the error returned from this, I've previously tried to do that elsewhere with no success.

From what I can tell the RPC error is constructed as a single error object from the returned body rather than a true representation of the original error chain, so errors.Is sees 

In this case it's returning `rpc error: code = Canceled desc = context canceled: draining` where neither `context.Cancelled` nor the original draining error match.

image

Comment (charleskorn) [reply pkg/scheduler/scheduler_test.go]: The error is a gRPC-style error, as you point out - you should be able to use `grpcutil.ErrorToStatus` from dskit to get the a `Status` that you can assert on.

Comment (monoxane) [reply pkg/scheduler/scheduler_test.go]: Thanks!

Comment (monoxane) [reply pkg/scheduler/scheduler_test.go]: I ended up having to IsEqual the `(*status.Status).Message()` and `(error).Error()`, as the `(*status.Status).Err()` still gave the entire error, but its now asserting on something at least.

**Review by charleskorn — APPROVED** [review]
Thanks for addressing my feedback!
