### PR TITLE
Cardinality API: tolerate single zone failures

### LINKED ISSUE #818: Calls to /cardinality/label_values fail during rollouts
**Describe the bug**
The `/cardinality/label_values` API fails if one (or more) ingesters are down, as is typical during a rollout.

**To Reproduce**

1. Start Mimir (SHA or version)
2. Shut down a single ingester / leave in ring. (e.g. rolling restart)
3. Make a request to `/api/prom/api/v1/cardinality/label_values`

**Expected behavior**
The API request should succeed.

**Environment:**

- Infrastructure: n/a
- Deployment tool: n/a

**Storage Engine**

- [x] Blocks
- [ ] Chunks

**Additional Context**

### PR DESCRIPTION
**Pull request by Logiraptor**
#### What this PR does

This PR changes the cardinality API to require only a majority of zones when zone aware replication is enabled. 

Previously, we required all zones to report successfully, then divided the result by the replication factor. This has two drawbacks:

1. We would _always_ have downtime for the cardinality API during a rollout
2. We would likely underestimate cardinality, because any ingester with missing samples will bring down the average across zones.

Now, we require only a majority of zones, like the rest of the read path. Secondly, it will now compute the _max_ value across zones instead of an average. This way, if a single zone is missing some data due to a rollout / crash / etc, its cardinality will be discarded in favor of whichever zone has the most data.

#### Which issue(s) this PR fixes or relates to

Fixes #818

#### Checklist

- [X] Tests updated
- [N/A] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by replay** [comment]
> This way, if a single zone is missing some data due to a rollout / crash / etc, its cardinality will be discarded in favor of whichever zone has the most data.

After a rolling restart all ingesters are going to be missing some samples, although different ones, so I think the result still won't be perfectly accurate. However, it's a better approximation than without this change for sure.

File: pkg/distributor/distributor.go [hunk 1]
```diff
@@ -1523,46 +1531,54 @@ func (cm *labelValuesCardinalityConcurrentMap) processLabelValuesCardinalityMess
...
-			// Label name existent
-			cm.cardinalityMap[item.LabelName][labelValue] += seriesCount
+
+			// Create a new map for the label value if it doesn't exist
+			if _, ok := cm.cardinalityMapByZone[item.LabelName][labelValue]; !ok {
+				cm.cardinalityMapByZone[item.LabelName][labelValue] = map[string]uint64{}
+			}
+
+			// Add the series count to the map
+			cm.cardinalityMapByZone[item.LabelName][labelValue][zone] += seriesCount
```
Comment (replay) [inline pkg/distributor/distributor.go:1559]: if in the end we take the max of each zone anyway, why do we need to store the series count per zone instead of only storing it if it's higher?

**Review by replay — APPROVED** [review]
This looks great, thanks!

**Review by bboreham — APPROVED** [review]
Nice.

File: pkg/distributor/distributor.go [hunk 2]
```diff
@@ -1460,32 +1460,40 @@ func (d *Distributor) labelValuesCardinality(ctx context.Context, labelNames []m
...
 		stream, err := client.LabelValuesCardinality(ctx, labelValuesReq)
 		if err != nil {
-			return nil, err
+			return struct{}{}, err
 		}
 		defer func() { _ = stream.CloseSend() }()
 
-		return nil, cardinalityConcurrentMap.processLabelValuesCardinalityMessages(stream)
-	})
+		return struct{}{}, cardinalityConcurrentMap.processLabelValuesCardinalityMessages(desc.Zone, stream)
```
Comment (dimitarvdimitrov) [inline pkg/distributor/distributor.go:1491]: Have you considered instead accumulating the streams in a slice and looping over them after `DoUntilQuorum` returns? It feels like that was the intended usage of `DoUntilQuorum` as opposed to consuming the result within the function.

File: pkg/distributor/distributor.go [hunk 3]
```diff
@@ -1501,20 +1509,20 @@ func toLabelValuesCardinalityRequest(labelNames []model.LabelName, matchers []*l
 }
 
 type labelValuesCardinalityConcurrentMap struct {
-	cardinalityMap map[string]map[string]uint64
-	lock           sync.Mutex
+	// cardinalityMapByZone stores a result for each zone.
```
Comment (dimitarvdimitrov) [inline pkg/distributor/distributor.go:1512]: nit: I expected that zone is the first key but it seems like it's the last

```suggestion
	// cardinalityMapByZone stores a result for each zone. map[label_name]map[label_value]map[zone]
```

File: pkg/distributor/distributor.go [hunk 4]
```diff
@@ -1523,46 +1531,54 @@ func (cm *labelValuesCardinalityConcurrentMap) processLabelValuesCardinalityMess
...
-	cardinalityItems := make([]*ingester_client.LabelValueSeriesCount, 0, len(cm.cardinalityMap))
-	// Adjust label values' series count based on the ingester's replication factor
-	for labelName, labelValueSeriesCountMap := range cm.cardinalityMap {
-		adjustedSeriesCountMap := make(map[string]uint64, len(labelValueSeriesCountMap))
-		for labelValue, seriesCount := range labelValueSeriesCountMap {
-			adjustedSeriesCountMap[labelValue] = seriesCount / uint64(replicationFactor)
+	cardinalityItems := make([]*ingester_client.LabelValueSeriesCount, 0, len(cm.cardinalityMapByZone))
+	// Adjust label values' series count to return the max value across zones
+	for labelName, labelValueSeriesCountMapByZone := range cm.cardinalityMapByZone {
+		labelValueSeriesCountMap := map[string]uint64{}
```
Comment (dimitarvdimitrov) [inline pkg/distributor/distributor.go:1573]: nit: this can be preallocated
```suggestion
		labelValueSeriesCountMap := make(map[string]uint64, len(labelValueSeriesCountMapByZone))
```

File: pkg/distributor/distributor.go [hunk 5]
```diff
@@ -1523,46 +1531,54 @@ func (cm *labelValuesCardinalityConcurrentMap) processLabelValuesCardinalityMess
...
 	defer cm.lock.Unlock()
 
 	for _, item := range message.Items {
-		if _, exists := cm.cardinalityMap[item.LabelName]; !exists {
-			// Label name nonexistent
-			cm.cardinalityMap[item.LabelName] = map[string]uint64{}
+
+		// Create a new map for the label name if it doesn't exist
+		if _, ok := cm.cardinalityMapByZone[item.LabelName]; !ok {
+			cm.cardinalityMapByZone[item.LabelName] = map[string]map[string]uint64{}
```
Comment (dimitarvdimitrov) [inline pkg/distributor/distributor.go:1548]: can this also be preallocated?
```suggestion
			cm.cardinalityMapByZone[item.LabelName] = make(map[string]map[string]uint64, len(item.LabelValueSeries))
```

File: pkg/distributor/distributor.go [hunk 6]
```diff
@@ -1460,32 +1460,40 @@ func (d *Distributor) labelValuesCardinality(ctx context.Context, labelNames []m
...
-	replicationSet.MaxErrors = 0
-	replicationSet.MaxUnavailableZones = 0
+	// If we have a single zone, we require all ingesters to respond.
+	if replicationSet.ZoneCount() == 1 {
+		replicationSet.MaxErrors = 0
+	}
 
 	cardinalityConcurrentMap := &labelValuesCardinalityConcurrentMap{
-		cardinalityMap: map[string]map[string]uint64{},
+		cardinalityMapByZone: map[string]map[string]map[string]uint64{},
```
Comment (dimitarvdimitrov) [inline pkg/distributor/distributor.go:1469]: i'm really good at spotting all the maps which aren't preallocated 
```suggestion
		cardinalityMapByZone: make(map[string]map[string]map[string]uint64, len(labelNames)),
```

File: pkg/distributor/distributor.go [hunk 7]
```diff
@@ -1687,29 +1733,55 @@ func (d *Distributor) UserStats(ctx context.Context) (*UserStats, error) {
...
 
-	totalStats := &UserStats{}
-	for _, resp := range resps {
-		r := resp.(*ingester_client.UserStatsResponse)
-		totalStats.IngestionRate += r.IngestionRate
-		totalStats.APIIngestionRate += r.ApiIngestionRate
-		totalStats.RuleIngestionRate += r.RuleIngestionRate
-		totalStats.NumSeries += r.NumSeries
+	var (
+		zoneIngestionRate     = map[string]float64{}
```
Comment (dimitarvdimitrov) [inline pkg/distributor/distributor.go:1765]: since those will be generally small maps it should be ok to not preallocate them (iirc smallest map size in go is 8 elements anyways)

**Review by dimitarvdimitrov — COMMENTED** [review]
mostly nitpicks, one of the usages of DoUntilQuorum seemed unusual. Otherwise LGTM!

File: pkg/distributor/distributor.go (hunk 3 above)
Comment (Logiraptor) [reply pkg/distributor/distributor.go]: Thanks, I had originally written it that way, but since we need to compare all zones for each label value, this structure made it easier to get them all in one place for `approximateFromZones`

File: pkg/distributor/distributor.go (hunk 2 above)
Comment (dimitarvdimitrov) [reply pkg/distributor/distributor.go:1491]: ah, that sounds great. Maybe a comment could help. This is merged now, so i don't insist you add it

File: pkg/distributor/distributor.go [hunk 8]
```diff
@@ -1460,32 +1460,40 @@ func (d *Distributor) labelValuesCardinality(ctx context.Context, labelNames []m
...
-	replicationSet.MaxErrors = 0
-	replicationSet.MaxUnavailableZones = 0
+	// If we have a single zone, we require all ingesters to respond.
+	if replicationSet.ZoneCount() == 1 {
+		replicationSet.MaxErrors = 0
+	}
 
 	cardinalityConcurrentMap := &labelValuesCardinalityConcurrentMap{
-		cardinalityMap: map[string]map[string]uint64{},
+		cardinalityMapByZone: make(map[string]map[string]map[string]uint64, len(labelNames)),
```
Comment (pracucci) [inline pkg/distributor/distributor.go:1469]: I just realised we have no benchmark on `labelValuesCardinality()`. I would be nice to have one to see the impact of changes we do it.
