### PR TITLE
Query-frontend: don't retry queries which error inside PromQL

### LINKED ISSUE #4637: Erroneous retry after over-limit error
#### Describe the bug

Mimir query-frontend retried a request after it had failed with this error:

```
ts=2023-03-31T09:44:40.112915729Z caller=retry.go:78 level=error user=<redacted> traceID=32a52c643e4c477f msg="error processing request" try=0 err="expanding series: the query exceeded the maximum number of chunks (limit: <redacted> chunks) (err-mimir-max-chunks-per-query). To adjust the related per-tenant limit, configure -querier.max-fetched-chunks-per-query, or contact your service administrator."
```

#### To Reproduce

1. Start Mimir (SHA 94a761f0)
2. Run a very big query.

#### Expected behavior

Should bail out on a `QueryLimiter` error.

#### Environment

- Infrastructure: Grafana Cloud.

### PR DESCRIPTION
**Pull request by bboreham**
#### What this PR does

Break out of the retry loop if the error has been decoded from a Prometheus error, or is a cancellation.

~Extra drive-by fix: don't log "context canceled" as an error in the querier.  This is noticeable when running `TestQueryFrontendErrorMessageParity/query_time_range_exceeds_the_limit`, for instance.~

#### Which issue(s) this PR fixes or relates to

Fixes #4637

#### Checklist

- [x] Tests updated
- NA Documentation added
- [x] `CHANGELOG.md` updated

### CODE REVIEW

File: pkg/frontend/querymiddleware/retry_test.go [hunk 1]
```diff
@@ -35,6 +37,7 @@ func TestRetry(t *testing.T) {
 		handler Handler
 		resp    Response
 		err     error
+		retr    int
```
Comment (56quarters) [inline pkg/frontend/querymiddleware/retry_test.go:40]: nit: could we call this `retries` or `expectedRetries`?

File: pkg/frontend/querymiddleware/retry_test.go [hunk 2]
```diff
@@ -73,14 +88,25 @@ func TestRetry(t *testing.T) {
...
+			h := newRetryMiddleware(&cl, 5, nil).Wrap(tc.handler)
 			resp, err := h.Do(context.Background(), nil)
 			require.Equal(t, tc.err, err)
 			require.Equal(t, tc.resp, resp)
+			require.Equal(t, tc.retr, cl.count)
 		})
 	}
 }
 
+type countingLogger struct {
```
Comment (56quarters) [inline pkg/frontend/querymiddleware/retry_test.go:101]: nit: Perhaps it's overkill for this, but my preference would be to add a new unexported method that returns the number of retries and assert based on that instead of something implicit like number of log calls.

e.g.

```go
func (r retry) doWithRetries(ctx context.Context, req Request) (Response, int, error) { /* ... */ }

func (r retry) Do(ctx context.Context, req Request) (Response, error) { 
    resp, _, err := r.doWithRetries(ctx, req)
    return resp, err
}
```

Comment (bboreham) [reply pkg/frontend/querymiddleware/retry_test.go]: Because this is used via the `querymiddleware.Handler` interface, calling into a different function requires a type assertion.

I noticed there is already a `metrics` which is counting retries, however checking the state of a Prometheus histogram is also ugly.

So, I put the metrics behind an interface and mocked that.  See what you think.

**Comment by bboreham** [comment]
The change to not log "context canceled" as an error in the querier actually broke query-frontend, so I have removed it from this PR.

File: pkg/frontend/querymiddleware/retry.go [hunk 3]
```diff
@@ -7,21 +7,27 @@ package querymiddleware
...
 	"github.com/go-kit/log/level"
 	"github.com/prometheus/client_golang/prometheus"
 	"github.com/prometheus/client_golang/prometheus/promauto"
 	"github.com/weaveworks/common/httpgrpc"
 
+	apierror "github.com/grafana/mimir/pkg/api/error"
 	util_log "github.com/grafana/mimir/pkg/util/log"
 )
 
+type intObservation interface {
```
Comment (colega) [inline pkg/frontend/querymiddleware/retry.go:22]: Nit, but should be:

```suggestion
type intObserver interface {
```

File: pkg/frontend/querymiddleware/retry.go [hunk 4]
```diff
@@ -7,21 +7,27 @@ package querymiddleware
...
+	Observe(int)
+}
+
 type retryMiddlewareMetrics struct {
 	retriesCount prometheus.Histogram
 }
 
-func newRetryMiddlewareMetrics(registerer prometheus.Registerer) *retryMiddlewareMetrics {
+func newRetryMiddlewareMetrics(registerer prometheus.Registerer) intObservation {
```
Comment (colega) [inline pkg/frontend/querymiddleware/retry.go:30]: I don't see the value in this, I think we could perfectly use `prometheus.Observer` inteface and call `float64` casting in all (1?) places.

File: pkg/frontend/querymiddleware/retry.go [hunk 5]
```diff
@@ -71,6 +81,10 @@ func (r retry) Do(ctx context.Context, req Request) (Response, error) {
 			return resp, nil
 		}
 
+		// Any error from the Prometheus API is non-retryable.
+		if apierror.IsAPIError(err) || errors.Is(err, context.Canceled) {
```
Comment (colega) [inline pkg/frontend/querymiddleware/retry.go:85]: I see that one of the apiError types is `TypeInternal`, can you explain in this comment why that one is also non-retryable?

Comment (bboreham) [reply pkg/frontend/querymiddleware/retry.go:85]: Well, this is complicated...
`TypeInternal` is mapped from Prometheus `errorInternal`.
Which is used in only a few places that we're interested in, but specifically `querier.NewErrorTranslateSampleAndChunkQueryable`.

So, I guess I should exclude that.

File: pkg/api/error/error.go [hunk 6]
```diff
@@ -115,3 +115,16 @@ func IsAPIError(err error) bool {
 	apiErr := &apiError{}
 	return errors.As(err, &apiErr)
 }
+
+// IsAPIError returns true if err is an apiError which should be failed and not retried.
+func IsNonretryableAPIError(err error) bool {
```
Comment (colega) [inline pkg/api/error/error.go:120]:
```suggestion
// IsNonRetryableAPIError returns true if err is an apiError which should be failed and not retried.
func IsNonRetryableAPIError(err error) bool {
```

**Review by colega — APPROVED** [review]
LGTM, please consider my comment.

File: pkg/frontend/querymiddleware/retry.go [hunk 7]
```diff
@@ -32,17 +34,21 @@ func newRetryMiddlewareMetrics(registerer prometheus.Registerer) *retryMiddlewar
 	}
 }
 
+func (m *retryMiddlewareMetrics) Observe(v float64) {
+	m.retriesCount.Observe(v)
+}
```
Comment (colega) [inline pkg/frontend/querymiddleware/retry.go:39]: What I meant is that the entire `retryMiddlewareMetrics` struct (and this method) isn't really necessary, as we can just return the histogram we've created. But it's not a big deal.

Comment (bboreham) [reply pkg/frontend/querymiddleware/retry.go:39]: That struct was in the code already.  I imagine it is following some common pattern, or being ready to collect more than one metric?
Either way, changing the way that works seems beyond what I want to achieve here; should be a separate PR.

Comment (colega) [reply pkg/frontend/querymiddleware/retry.go:39]: Agree, I'm not blocking on this. 👍
