### PR TITLE
distributor: In-memory series approximation to take into account that number of zones may be large than RF

### LINKED ISSUE #7738: Cardinality API returns wrong number of in-memory series when using 5 zones and RF=3
#### Describe the bug

`/api/v1/cardinality/label_values` endpoint returns number of in-memory or active series as part of the response.

This number can be wrong in a setup with 5 zones and replication factor three.

Observed in-memory series per zone:
* 22218014
* 22159603
* 22074077
* 22204646
* 22505493

Total in-memory series: 110992564. Because replication factor is three, that means 110992564 / 3 = 37M series before replication.

However `/api/v1/cardinality/label_values` reports ~22M series in `series_count_total` field.

Configuration:
* Mimir 2.11, with default values for ingester request minimization (= true).
* 5 zones
* replication factor 3

Details:
* `/api/v1/cardinality/label_values` [uses](https://github.com/grafana/mimir/blob/42ccb78851f02cfe70e5681332fc2486b206a1f3/pkg/distributor/distributor.go#L1638-L1648) distributors' `UserStats` ([code from release-2.11](https://github.com/grafana/mimir/blob/42ccb78851f02cfe70e5681332fc2486b206a1f3/pkg/distributor/distributor.go#L2003-L2066)) to compute in-memory series. UserStats will query in-memory series from zones until the quorum is reached. After reaching quorum, [`approximateFromZones` function](https://github.com/grafana/mimir/blob/42ccb78851f02cfe70e5681332fc2486b206a1f3/pkg/distributor/distributor.go#L1865-L1893) is used to compute approximate number of in-memory series. When using multi-zone setup, this function simply returns maximum of per-zone values. **This would only be correct when number of zones is equal to replication factor.**

Expected behaviour: computation of number of series should correctly handle the case where number of zones is different from replication factor.

### PR DESCRIPTION
**Pull request by narqo**
#### What this PR does

This PR updates the distributor's internals, that do the approximation of the number of in-memory series, for the `/api/v1/cardinality/label_values` API endpoint. Now, if the number of zones where ingesters run is larger than the replication factor (RF), the approximation falls back to the single zone logic. This seems more accurate, than returning the value of the largest zone.

#### Which issue(s) this PR fixes or relates to

Fixes #7738

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/distributor/distributor_test.go [hunk 1]
```diff
@@ -3729,6 +3729,34 @@ func TestDistributor_UserStats(t *testing.T) {
...
+				},
+				"zone-d": {
+					makeWriteRequest(0, 1, 0, false, false, "series_4", "series_5", "series_1"),
+				},
+				"zone-e": {
+					makeWriteRequest(0, 1, 0, false, false, "series_5", "series_1", "series_2"),
+				},
+			},
+			// We pushed 5 series but every series has been successfully replicated only to 3 ingesters (in different zones).
+			expectedSeries: 4,
```
Comment (dimitarvdimitrov) [inline pkg/distributor/distributor_test.go:3758]: i can't understand why 4 in this case? Shouldn't it be 3 instead? `(3 /*zone-a*/ + 3 /*zone-b*/ + 3 + 3 + 3) / 5 /*replication_factor*/ = 3`

Comment (pracucci) [reply pkg/distributor/distributor_test.go:3758]: I've originally written this test and I confirm what Vladimir is saying. Our count is just an approximation when minimize ingester requests in is use (or even when it's used used but we stop processing ingesters data once quorum is reached).

However, I've the feeling this assertion may be flaky for the test run with `minimizeIngesterRequests: false` because, based on timing conditions, it could also count 5 (case when all ingesters response are processed before we realise quorum is reached and we stop processing response from more ingesters).

**Review by pracucci — APPROVED** [review]

File: pkg/distributor/distributor_test.go (hunk 1 above)
Comment (pracucci) [reply pkg/distributor/distributor_test.go:3758]: I've approved the PR but I'm no more sure that this change is an improvement over the current logic. It's probably an improvement when minimise ingesters requests is disabled, but I think it still return the wrong number when minimize is enabled.

Comment (narqo) [reply pkg/distributor/distributor_test.go]: Was thinking about the problem here: what we do the approximation as follows,

```
MAX(valueAcrossZones) * zonesTotal / RF
```

I think, for multi-zonal deployments, this should return a better approximation for both disable and enable of minimise ingesters requests.

File: pkg/distributor/distributor.go [hunk 2]
```diff
@@ -2472,10 +2482,10 @@ func (d *Distributor) UserStats(ctx context.Context, countMethod cardinality.Cou
 		// so regardless the number of zones we have it's behaving like multi-zone is always enabled.
 		isMultiZone := d.cfg.IngestStorageConfig.Enabled || replicationSet.ZoneCount() > 1
 
-		totalStats.IngestionRate += approximateFromZones(isMultiZone, d.ingestersRing.ReplicationFactor(), zoneIngestionRate)
-		totalStats.APIIngestionRate += approximateFromZones(isMultiZone, d.ingestersRing.ReplicationFactor(), zoneAPIIngestionRate)
-		totalStats.RuleIngestionRate += approximateFromZones(isMultiZone, d.ingestersRing.ReplicationFactor(), zoneRuleIngestionRate)
-		totalStats.NumSeries += approximateFromZones(isMultiZone, d.ingestersRing.ReplicationFactor(), zoneNumSeries)
+		totalStats.IngestionRate += approximateFromZones(isMultiZone, replicationSet.ZoneCount(), d.ingestersRing.ReplicationFactor(), zoneIngestionRate)
```
Comment (pracucci) [inline pkg/distributor/distributor.go:2485]: When the experimental ingest storage in enabled, I think the value computed here is wrong because what we really want is the "max per zone". I reused `approximateFromZones()` for simplicity, and I think the math was correct before this PR, but maybe at this point it's better if we have a different "approximate" function for the ingest storage.

When ingest storage is in use, a replication set is the set of ingesters for 1 partition. Given each set (which means given each partition) we want to get the max value among them. That's all.

File: pkg/distributor/distributor.go [hunk 3]
```diff
@@ -2250,14 +2254,20 @@ func approximateFromZones[T ~float64 | ~uint64](isMultiZone bool, replicationFac
...
 		}
-		return max
+		if zonesTotal <= replicationFactor {
+			return max
+		}
+		// When the number of zones is larger than the replication factor, we factor
+		// that into the approximation. We multiply the max of all zones to a ratio
+		// of number of zones to the replication factor to approximate how series
+		// are spread across zones.
+		return T(math.Round(float64(max) * float64(zonesTotal) / float64(replicationFactor)))
```
Comment (pracucci) [inline pkg/distributor/distributor.go:2264]: I think this change is fine (correct) for the case ingest storage is not in use, so I would keep it.

File: pkg/distributor/distributor.go [hunk 4]
```diff
@@ -2034,7 +2038,7 @@ func (cm *labelValuesCardinalityConcurrentMap) toResponse(isMultiZone bool, repl
 			total := uint64(0)
 
 			for _, countByZone := range dataByReplicationSet {
-				total += approximateFromZones(isMultiZone, replicationFactor, countByZone)
+				total += approximateFromZones(isMultiZone, zonesTotal, replicationFactor, countByZone)
```
Comment (pracucci) [inline pkg/distributor/distributor.go:2041]: Similar to the comment left on UserStats(), when the ingest storage is enabled here we simply want to get the max of each replication set.

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, thanks :shipit:

**Review by pracucci — APPROVED** [review]
LGTM, thanks!
