### PR TITLE
[ENHANCEMENT] Add `mimir-http-prefix` option to introduce a prefix for Mimir URL when use legacy routes.

### LINKED ISSUE #8018: mimirtool load rules not working with api.prometheus_http_prefix different than /prometheus
#### Describe the bug
mimirtool 2.12
./mimirtool rules load rules.yml will not work if the mimir "prometheus_http_prefix:" is changed from "/prometheus" to "/"

Working:
```yaml
api:
    prometheus_http_prefix: /prometheus
```

Not working
```yaml
api:
    prometheus_http_prefix: /
```

It looks like the "POST Request" is wrong if the  "--use-legacy-routes" parameter is used compared to "--no-use-legacy-routes"

WRONG POST request:
```
root@ubiquiti:/opt/mimir# ./mimirtool rules load ./rules.yml --address="http://192.168.178.51:9009" --id=anonymous --tls-insecure-skip-verify --use-legacy-routes --log.level="debug"
INFO[0000] log level set to debug
group: 'mimir_api_1', ns: 'rules'
/api/v1/rules/rules/mimir_api_1
DEBU[0000] sending request to Grafana Mimir API          method=GET url="http://192.168.178.51:9009/api/v1/rules/rules/mimir_api_1"
DEBU[0000] checking response                             status="404 Not Found"
DEBU[0000] response                                      body="404 page not found\n" status="404 Not Found"
DEBU[0000] sending request to Grafana Mimir API          method=POST url="http://192.168.178.51:9009/api/v1/rules/rules"
DEBU[0000] checking response                             status="404 Not Found"
DEBU[0000] response                                      body="404 page not found\n" status="404 Not Found"
ERRO[0000] unable to load rule group                     error="POST request to http://192.168.178.51:9009/api/v1/rules/rules failed: requested resource not found" group=mimir_api_1 namespace=rules
mimirtool: error: load operation unsuccessful, try --help
root@ubiquiti:/opt/mimir#
```
error="POST request to http://192.168.178.51:9009**/api/v1/rules/rules** failed

CORRECT Post request:
```
root@ubiquiti:/opt/mimir# ./mimirtool rules load ./rules.yml --address="http://192.168.178.51:9009" --id=anonymous --tls-insecure-skip-verify --no-use-legacy-routes --log.level="debug"
INFO[0001] log level set to debug
group: 'mimir_api_1', ns: 'rules'
/prometheus/config/v1/rules/rules/mimir_api_1
DEBU[0001] sending request to Grafana Mimir API          method=GET url="http://192.168.178.51:9009/prometheus/config/v1/rules/rules/mimir_api_1"
DEBU[0001] checking response                             status="404 Not Found"
DEBU[0001] response                                      body="group does not exist\n" status="404 Not Found"
DEBU[0001] sending request to Grafana Mimir API          method=POST url="http://192.168.178.51:9009/prometheus/config/v1/rules/rules"
DEBU[0001] checking response                             status="202 Accepted"
```
method=POST url="http://192.168.178.51:9009/prometheus**/config/v1/rules/rules**"
DEBU[0001] checking response                             status="202 Accepted"

#### To Reproduce

```yaml
api:
    prometheus_http_prefix: /
```

./mimirtool rules load ./rules.yml --address="http://192.168.178.51:9009" --id=anonymous --tls-insecure-skip-verify --use-legacy-routes --log.level="debug"

#### Expected behavior

It should be possible to use mimirtool to load ules with differnet prometheus_http_prefixes.

#### Environment

- Infrastructure: bare-metal
- 2.12
- mimirtool-amd64

### PR DESCRIPTION
**Pull request by ying-jeanne**
[ENHANCEMENT] Add `mimir-http-prefix` option to introduce a prefix for Mimir URL when use legacy routes.

#### What this PR does
clean up some mimirtool bugs, adding mimir-http-prefix for mimir client when use legacy routes 
#### Which issue(s) this PR fixes or relates to

Fixes #8018

#### Checklist

- [x] Tests updated.
- [x] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [x] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/mimirtool/client/client.go [hunk 1]
```diff
@@ -97,7 +98,10 @@ func New(cfg Config) (*MimirClient, error) {
 
 	path := rulerAPIPath
 	if cfg.UseLegacyRoutes {
-		path = legacyAPIPath
+		var err error
+		if path, err = url.JoinPath(cfg.MimirHTTPPrefix, legacyAPIPath); err != nil {
+			return nil, err
+		}
 	}
```
Comment (lamida) [inline pkg/mimirtool/client/client.go:105]: Should we validate that the user mustn't set `MimirHTTPPrefix` if `UseLegacyRoutes` is false?

File: CHANGELOG.md [hunk 2]
```diff
@@ -101,6 +101,7 @@
 
 * [CHANGE] Deprecated `--rule-files` flag in favor of CLI arguments. #7756
 * [BUGFIX] Fix panic in `loadgen` subcommand. #7629
+* [ENHANCEMENT] Add `mimir-http-prefix` option to introduce a prefix for Mimir URL when use legacy routes. #8069
```
Comment (lamida) [inline CHANGELOG.md:104]: Nit
```suggestion
* [ENHANCEMENT] Add `mimir-http-prefix` configuration to set the Mimir URL prefix when using legacy routes. #8069
```

**Review by lamida — APPROVED** [review]
In general LGTM. But I left two nit comments.

File: pkg/mimirtool/client/client.go (hunk 1 above)
Comment (ying-jeanne) [reply pkg/mimirtool/client/client.go:105]: this could be tricky to check here, since `MimirHTTPPrefix` has a default value /prometheus, in client we will not able to distinguish the not set and default value.

**Review by lamida — APPROVED** [review]
LGTM

**Comment by dimitarvdimitrov** [comment]
a late follow-up: can you update the docs for Mimirtool https://github.com/grafana/mimir/blob/51498b2054c0bb836f9aba427fd467f43c37c206/docs/sources/mimir/manage/tools/mimirtool.md?
