### PR TITLE
Fix ruler flaky tests

### LINKED ISSUE #2803: Flaky TestRuler_Rules
As seen at https://github.com/grafana/mimir/runs/7956562047
Re-run at https://github.com/grafana/mimir/runs/7956932204 passed.

```
--- FAIL: TestRuler_Rules (0.06s)
    --- FAIL: TestRuler_Rules/rules_-_user1 (0.02s)
        ruler_test.go:283: 
            	Error Trace:	/__w/mimir/mimir/pkg/ruler/ruler_test.go:283
            	Error:      	"[]" should have 1 item(s), but has 0
            	Test:       	TestRuler_Rules/rules_-_user1
```

### PR DESCRIPTION
**Pull request by pracucci**
#### What this PR does
`TestRuler_Rules` is flaky. The problem is that some ruler tests both start the ruler service **and** call `ruler.syncRules()`. The `ruler.syncRules()` is not concurrency safe, because of the rules config file mapper (it's not safe). The ruler logic is OK, but tests are not and they suffer some race conditions.

In this PR I'm removing any call to `ruler.syncRules()` from tests, just relying on the sync done by the ruler service itself and introducing a polling to wait until the desired condition is met.

#### Which issue(s) this PR fixes or relates to

Fixes #2803

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ruler/ruler.go [hunk 1]
```diff
@@ -458,6 +458,7 @@ func (r *Ruler) run(ctx context.Context) error {
 	}
 }
 
+// It's not safe to call this function concurrently.
```
Comment (56quarters) [inline pkg/ruler/ruler.go:461]: nit: Can you expand on this comment a bit? Maybe something like "we expect this is only called from the service `run` method"

**Review by 56quarters — APPROVED** [review]
LGTM
