### PR TITLE
mimirtool: add TLS client flags to remote-read subcommands

### LINKED ISSUE #8274: mimirtool: Unable to configure client TLS for `remote-read` and other commands
Using mimirtool to interact with a mimir instance configured for TLS Client Auth there is no way to configure the client cert and key to use for communicating with mimir. The `alertmanager` command has `--tls-ca-path`, `--tls-cert-path`, and `--tls-key-path`, but using this with `remote-read` errors with:
> mimirtool: error: unknown long flag '--tls-cert-path', try --help

I've also tried setting `MIMIR_TLS_CERT_PATH` and `MIMIR_TLS_KEY_PATH`, but this also errored:
> mimirtool: error: error sending request: Post "https://xxx:8080/prometheus/api/v1/read": remote error: tls: certificate required, try --help

### PR DESCRIPTION
**Pull request by alliasgher**
#### What this PR does

`mimirtool alertmanager` and `mimirtool rules` accept `--tls-ca-path`, `--tls-cert-path`, `--tls-key-path`, and `--tls-insecure-skip-verify` (plus the matching `MIMIR_TLS_*` env vars), but `mimirtool remote-read` does not, so anyone running Mimir with TLS client authentication hits:

> mimirtool: error: unknown long flag '--tls-cert-path', try --help

This PR registers the same four flags on the shared `export`/`dump`/`stats` flag set inside `pkg/mimirtool/commands/remote_read.go`, and wires them through `config_util.TLSConfig` on the `remote.NewReadClient` call so `remote-read` now honours the same TLS configuration as the other subcommands.

No behavior change when the flags are unset.

#### Which issue(s) this PR fixes or relates to

Fixes #8274

#### Checklist

- [x] Tests updated — existing `TestParseArgsAndPrepareClient` still passes; TLS defaults keep pre-existing behavior.
- [x] Documentation added — CLI `--help` auto-exposes the new flags with descriptions matching the other subcommands.
- [x] `CHANGELOG.md` updated
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features — N/A, not an experimental flag.

---

> [!NOTE]
> **Low Risk**
> Low risk, additive CLI/client configuration only; behavior is unchanged unless TLS flags/env vars are set. Main risk is misconfiguration impacting connectivity to the remote-read endpoint.
> 
> **Overview**
> Adds TLS client configuration support to `mimirtool remote-read` (`export`/`dump`/`stats`) via new flags/env vars for CA, client cert/key, and optional certificate verification skipping.
> 
> Wires these options into the `remote.NewReadClient` HTTP `TLSConfig`, and documents the enhancement in `CHANGELOG.md`.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 8bd53f14288014df2765ed43504deb9918c3a40f. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: pkg/mimirtool/commands/remote_read.go [hunk 1]
```diff
@@ -91,6 +91,11 @@ type RemoteReadCommand struct {
 	apiKey   string
 	apiUser  string
 
+	tlsCAPath             string
```
Comment (56quarters) [inline pkg/mimirtool/commands/remote_read.go:94]: I realize this was already inconsistent but would you mind refactoring this to use `client.Config` to bundle all the auth settings and `address` together, similar to how the `rules` command does?

**Review by 56quarters — CHANGES_REQUESTED** [review]
Thank you for this PR. This looks reasonable to me with one ask to clean up some existing inconsistency. Thanks!

File: pkg/mimirtool/commands/remote_read.go (hunk 1 above)
Comment (alliasgher) [reply pkg/mimirtool/commands/remote_read.go:94]: Happy to do this. Since the original ask in this PR was just adding TLS client flags, would you prefer the `client.Config` refactor as a separate follow-up PR so the cleanup stays distinct from the new flags?

Comment (56quarters) [reply pkg/mimirtool/commands/remote_read.go:94]: Sure, good idea.

File: CHANGELOG.md [hunk 2]
```diff
@@ -945,6 +946,7 @@
 * [BUGFIX] Fix issue where `remote-read` doesn't behave like other mimirtool commands for authentication. #11402
 * [BUGFIX] Fix issue where `remote-read export` could omit some samples if the query time range spans multiple blocks. #12025
 * [BUGFIX] Fix issue where `remote-read export` could omit some output blocks in the list printed to the console or fail with `read/write on closed pipe`. #12025
+* [BUGFIX] Add `--tls-ca-path`, `--tls-cert-path`, `--tls-key-path`, and `--tls-insecure-skip-verify` flags (and the matching `MIMIR_TLS_*` env vars) to the `remote-read` subcommands so they can talk to Mimir instances that require TLS client authentication, matching the other mimirtool subcommands. #8274
```
Comment (56quarters) [inline CHANGELOG.md]: This change should only have a single changelog entry. Can you remove this bugfix one?

**Review by 56quarters — APPROVED** [review]
LGTM, thanks!

File: CHANGELOG.md (hunk 2 above)
Comment (alliasgher) [reply CHANGELOG.md]: Done in 8bd53f1.
