### PR TITLE
s3: Allow disabling dual-stack endpoints

### LINKED ISSUE #7382: S3 backend does not work with VPC Interface Endpoints (dualstack not supported)
#### Describe the bug

I file this as a software bug though for now it could be considered a documentation bug because it can't be fixed until minio/minio-go#1766 is resolved: The library auto-detects AWS endpoints and force-rewrites them to their dualstack variant which is surprising and does not work in our context.

We are deploying Mimir in an enterprise environment. One of the policies (enforced by some central firewalling and/our routing) is that we can't connect to any public IPv4 addresses but must stay within the RFC1918 IP range. This includes the public AWS endpoints.

To be able to use them we deploy VPC Interface Endpoints and enable the [Private DNS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html#private-dns) option which will override s3.region.amazonaws.com in the local resolver and point it to the local endpoint. But S3 VPC Endpoints [do not support dualstack](https://docs.aws.amazon.com/AmazonS3/latest/userguide/dual-stack-endpoints.html#dual-stack-endpoints-description) yet so the DNS name s3.dualstack.region.amazonaws.com is not overridden.

Our current workaround is to use the Regional Names. So this works (but is complicated to maintain across accounts):
```
common:
  storage:
    backend: s3
    s3:
      endpoint: bucket.vpce-0c890e7af692eca77-54c6308e.s3.eu-central-1.vpce.amazonaws.com
      bucket_name: example-mimir-int-main
      region: eu-central-1
```

But this doesn't:
```
common:
  storage:
    backend: s3
    s3:
      endpoint: s3.eu-central-1.amazonaws.com
      bucket_name: example-mimir-int-main
      region: eu-central-1
```

#### To Reproduce
I think these steps should be enough to emulate our environment:

1. Prepare your VPC (subnets, resolvers, ...)
2. Create a security group which allows communication within the VPC CIDR range only
3. Create an S3 VPC Endpoint with Private DNS enabled
4. Create an EC2 instance, install Mimir
5. Configure Mimir to use an S3 storage backend using the endpoint name `s3.eu-central-1.amazonaws.com` (adopt to your region)
6. Start Mimir (2.11.0)

#### Expected behavior
Mimir should resolve `s3.eu-central-1.amazonaws.com` to an IP address within the VPC and start up.

#### Environment

- Infrastructure: AWS EC2
- Deployment tool: Ansible

#### Additional Context

```
Feb 14 13:08:40 i-0cb71db391d615e9f.eu-central-1.compute.internal mimir[119162]: ts=2024-02-14T13:08:40.538637541Z caller=memberlist_client.go:561 level=info msg="memberlist fast-join finished" joined_nodes=3 elapsed_time=131.174784ms
Feb 14 13:08:40 i-0cb71db391d615e9f.eu-central-1.compute.internal mimir[119162]: ts=2024-02-14T13:08:40.540366115Z caller=memberlist_client.go:573 level=info phase=startup msg="joining memberlist cluster" join_members=example-mimir-int-0.example-sandbox-1.eu-central-1.aws.example.com,example-mimir-int-1.example-sandbox-1.eu-central-1.aws.example.com,example-mimir-int-2.example-sandbox-1.eu-central-1.aws.example.com
Feb 14 13:08:40 i-0cb71db391d615e9f.eu-central-1.compute.internal mimir[119162]: ts=2024-02-14T13:08:40.721495949Z caller=memberlist_client.go:580 level=info phase=startup msg="joining memberlist cluster succeeded" reached_nodes=3 elapsed_time=181.04815ms
Feb 14 13:09:10 i-0cb71db391d615e9f.eu-central-1.compute.internal mimir[119162]: ts=2024-02-14T13:09:10.434945832Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="3 errors: blocks storage: unable to successfully send a request to object storage: Get \"https://example-mimir-int-main.s3.dualstack.eu-central-1.amazonaws.com/blocks/sanity-check-at-startup\": context deadline exceeded; alertmanager storage: unable to successfully send a request to object storage: Get \"https://example-mimir-int-main.s3.dualstack.eu-central-1.amazonaws.com/sanity-check-at-startup\": context deadline exceeded; ruler storage: unable to successfully send a request to object storage: Get \"https://example-mimir-int-main.s3.dualstack.eu-central-1.amazonaws.com/sanity-check-at-startup\": context deadline exceeded"
```

### PR DESCRIPTION
**Pull request by narqo**
#### What this PR does

This one adds a new configuration `s3.dualstack-enabled=true`, that allows user to disable S3 client from resolving the endpoint into dual-stack endpoint. The https://github.com/grafana/mimir/issues/7382 and https://github.com/minio/minio-go/issues/1766 explain the use cases where this can be needed.

#### Which issue(s) this PR fixes or relates to

Fixes #7382

#### Checklist

- [ ] Tests updated.
- [x] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/storage/bucket/s3/config.go [hunk 1]
```diff
@@ -152,6 +153,7 @@ func (cfg *Config) RegisterFlagsWithPrefix(prefix string, f *flag.FlagSet) {
 	f.Uint64Var(&cfg.PartSize, prefix+"s3.part-size", 0, "The minimum file size in bytes used for multipart uploads. If 0, the value is optimally computed for each object.")
 	f.BoolVar(&cfg.SendContentMd5, prefix+"s3.send-content-md5", false, "If enabled, a Content-MD5 header is sent with S3 Put Object requests. Consumes more resources to compute the MD5, but may improve compatibility with object storage services that do not support checksums.")
 	f.Var(newBucketLookupTypeValue(s3.AutoLookup, &cfg.BucketLookupType), prefix+"s3.bucket-lookup-type", fmt.Sprintf("Bucket lookup style type, used to access bucket in S3-compatible service. Default is auto. Supported values are: %s.", strings.Join(supportedBucketLookupTypes, ", ")))
+	f.BoolVar(&cfg.DualstackEnabled, prefix+"s3.dualstack-enabled", true, "When enabled, resolves AWS S3 endpoint into the dual IPv4/IPv6 endpoint for the configured region.")
```
Comment (narqo) [inline pkg/storage/bucket/s3/config.go:156]: > [..] into the dual IPv4/IPv6 endpoint for the configured region

I'm not a fan of the wording here, but I took it from [`aws-cli s3` help][1] :)

[1]: https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html#use-dualstack-endpoint

**Comment by sid-jar** [comment]
+1, @narqo , This similar issue is a blocker in our case as well, and hence we'd also expect the changes to be in effect pretty soon. 

@jdbaldry , when can we expect the merge to happen ?? Thanks

File: pkg/storage/bucket/s3/config.go (hunk 1 above)
Comment (jdbaldry) [reply pkg/storage/bucket/s3/config.go:156]: Great idea to reuse the existing AWS documentation for consistency. I am not sure if their technical writing team review the CLI help but I imagine they do review the documentation pages and it has a similar wording:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/dual-stack-endpoints.html#:~:text=direct%20all%20Amazon%20S3%20requests%20made%20by%20the%20s3%20and%20s3api%20AWS%20CLI%20commands%20to%20the%20dual%2Dstack%20endpoint%20for%20the%20specified%20region

```suggestion
	f.BoolVar(&cfg.DualstackEnabled, prefix+"s3.dualstack-enabled", true, "When enabled, direct all AWS S3 requests to the dual-stack IPv4/IPv6 endpoint for the configured region.")
```

Feel free to use whichever you think is most understandable to a Mimir user.

**Review by jdbaldry — APPROVED** [review]
Merge requires one of @grafana/mimir-maintainers to review the code but the docs changes LGTM

File: CHANGELOG.md [hunk 2]
```diff
@@ -69,6 +69,7 @@
 * [ENHANCEMENT] Query-frontend: be able to block remote read queries via the per tenant runtime override `blocked_queries`. #8372 #8415
 * [ENHANCEMENT] Query-frontend: added `remote_read` to `op` supported label values for the `cortex_query_frontend_queries_total` metric. #8412
 * [ENHANCEMENT] Query-frontend: log the overall length and start, end time offset from current time for remote read requests. The start and end times are calculated as the miminum and maximum times of the individual queries in the remote read request. #8404
+* [ENHANCEMENT] Storage Provider: `-<prefix>.s3.dualstack-enabled=true` that allows disabling S3 client from resolving AWS S3 endpoint into dual-stack IPv4/IPv6 endpoint. #8405
```
Comment (pstibrany) [inline CHANGELOG.md:72]:
```suggestion
* [ENHANCEMENT] Storage Provider: Added option `-<prefix>.s3.dualstack-enabled` that allows disabling S3 client from resolving AWS S3 endpoint into dual-stack IPv4/IPv6 endpoint. Defaults to true. #8405
```

File: pkg/storage/bucket/s3/bucket_client.go [hunk 3]
```diff
@@ -60,6 +60,7 @@ func newS3Config(cfg Config) (s3.Config, error) {
 		PutUserMetadata:    putUserMetadata,
 		SendContentMd5:     cfg.SendContentMd5,
 		SSEConfig:          sseCfg,
+		DisableDualstack:   !cfg.DualstackEnabled,
```
[the remark this answers is not in the document]
Comment (pstibrany) [reply pkg/storage/bucket/s3/bucket_client.go:63]: 👍  `DualstackEnabled` also follows our conventions for naming arguments.

**Review by pstibrany — APPROVED** [review]
Thank you.

**Comment by sid-jar** [comment]
Hi @pstibrany @jdbaldry, would there be a build released on docker anytime soon on this change ??

**Comment by narqo** [comment]
> would there be a build released on docker anytime soon?

In the beginning of each week the CI cuts a new weekly release, pushes it to docker hub and also updates helm chart.

**Comment by sid-jar** [comment]
I tried using this image tag [2.13.0-rc.0](https://hub.docker.com/layers/grafana/mimir/2.13.0-rc.0/images/sha256-9d57eb9e9cd0b9a5474577ee27d7185aaa420889d6b66d4f7c387eb78d55567d?context=explore) , but I still face issues regarding this. Sharing the config below

ERROR: 
`error loading config from /etc/mimir/mimir.yaml: Error parsing config file: yaml: unmarshal errors:
  line 24: field dualstack-enabled not found in type s3.Config`
  
  
```
config:
      s3:
        bucket_name: mimir-storage-bucket
        region: ap-south-1
        endpoint: s3.ap-south-1.amazonaws.com
        insecure: false
        dualstack-enabled: false
```

**Comment by narqo** [comment]
The feature didn't end up to 2.13. It required bumping the versions of core-dependencies in r295 weekly, which we didn't want to do in the last minute of the release.

You can test it with r296 weekly, that was cut on Monday. See [`grafana/mimir:r296-xxx`](https://hub.docker.com/r/grafana/mimir/tags?page=&page_size=&ordering=&name=r296)

**Comment by yebolenko** [comment]
I tried grafana/mimir:r296-3410422
still the same error:
error loading config from /etc/mimir/mimir.yaml: Error parsing config file: yaml: unmarshal errors:
  line 13: field dualstack-enabled not found in type s3.Config
  line 43: field dualstack-enabled not found in type s3.Config
  line 120: field dualstack-enabled not found in type s3.Config
  
It's my config:
  structuredConfig:
    usage_stats:
      enabled: false
      installation_mode: helm
    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: "mimir-alertmanager"
        endpoint: "s3.cn-north-1.amazonaws.com.cn"
        region: "cn-north-1"
        insecure: true
        dualstack-enabled: false
    blocks_storage:
      backend: s3
      s3:
        bucket_name: "mimir-blocks"
        endpoint: "s3.cn-north-1.amazonaws.com.cn"
        region: "cn-north-1"
        insecure: true
        dualstack-enabled: false
    ruler_storage:
      backend: s3
      s3:
        bucket_name: "mimir-ruler"
        endpoint: "s3.cn-north-1.amazonaws.com.cn"
        region: "cn-north-1"
        insecure: true
        dualstack-enabled: false

**Comment by yebolenko** [comment]
are you sure that property is named dualstack-enabled?

**Comment by 56quarters** [comment]
> are you sure that property is named dualstack-enabled?

It's not. YAML configuration settings always have underscores while CLI flags always have dashes: [code](https://github.com/grafana/mimir/blob/1cfb65777a4dbf21c85b1467e67b925e32e3042e/pkg/storage/bucket/s3/config.go#L125)

It should be `dualstack_enabled` if it's ending up a in a YAML configuration file passed to Mimir.

**Comment by yebolenko** [comment]
thank you for pointing on this.
after this change, I get such error:
ts=2024-06-26T19:23:25.609453896Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="2 errors: blocks storage: unable to successfully send a request to object storage: Get \"http://**mimir-blocks.s3.cn-north-1.amazonaws.com.cn**/sanity-check-at-startup\": context deadline exceeded; ruler storage: unable to successfully send a request to object storage: Get \"http://mimir-ruler.s3.cn-north-1.amazonaws.com.cn/sanity-check-at-startup\": context deadline exceeded"
it's my setup for mimir-blocks:
blocks_storage:
backend: s3
s3:
bucket_name: "mimir-blocks"
endpoint: "s3.cn-north-1.amazonaws.com.cn"
region: "cn-north-1"
insecure: true
dualstack_enabled: false
Is my endpoint set as expected?

**Comment by 56quarters** [comment]
Can you please start a discussion instead of replying to this merged PR?

**Comment by yebolenko** [comment]
I opened this issue: https://github.com/grafana/mimir/issues/8545
I will very appreciate if you can help
