### PR TITLE
Do not consider out-of-order blocks when filtering compactable jobs

### LINKED ISSUE #7279: Compactor does not compact when blocks are uploaded late
#### Describe the bug

The compactor currently has logic that will [skip first level compaction jobs](https://github.com/grafana/mimir/blob/845432f84f9e6b3d0e99525ff4d5a828196f4664/pkg/compactor/bucket_compactor.go#L998-L1014) if any of the blocks in the job were uploaded recently, relative to the `first_level_compaction_wait_period` setting (25m default). This works well under normal circumstances, but when blocks are being uploaded late for earlier time periods, such as because they contain out-of-order data or because not enough data was present to perform compaction earlier, those blocks effectively prevent blocks in the same job from being compacted.

For example, consider a set of blocks that cover the same time range and are grouped into the same job:

| Block                         | Upload time             | minT               | maxT             | 
|----------------------------|-------------------------|-------------------------|-------------------------|
| A | 2024-02-01T21:05:00Z | 2024-02-01T18:00:00Z | 2024-02-01T20:00:00Z|
| B | 2024-02-01T21:09:00Z | 2024-02-01T18:00:00Z | 2024-02-01T20:00:00Z|
| C | 2024-02-01T21:27:00Z | 2024-02-01T18:00:00Z | 2024-02-01T20:00:00Z|

At T=21:40, enough time has elapsed for the first two blocks to be compacted. But if new blocks are being uploaded, such as the third block above, it prevents the others in the group from being compacted. In practice, ongoing uploads of out-of-order blocks for an earlier time period can cause this.

#### To Reproduce

Enable OOO blocks and write samples for older time periods, for example, up to 2 hours after that period is over. When head compactions occur and the blocks are uploaded, these should prevent previously uploaded blocks in the same job from compacting.

#### Expected behavior

Blocks should be eligible for compaction based on the current time, relative to `first_level_compaction_wait_period`, not just based on the max upload/modified time of the blocks in the job. We should also consider when blocks are expected to be uploaded though, since early compaction may cause some blocks to be uploaded before others for the same time period.

### PR DESCRIPTION
**Pull request by jhalterman**
#### What this PR does

This PR excludes out-of-order blocks when deciding if a job should be filtered based on whether the first level compaction wait period has elapsed. This ensures that out-of-order blocks, which may be uploaded late, do not prevent compaction for a job containing blocks that were uploaded earlier.

#### Which issue(s) this PR fixes or relates to

Fixes #7279

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### Testing

I ran this for a day with many OOO blocks being created, and did not observe any compactions being skipped due to OOO blocks.

### CODE REVIEW

**Review by pstibrany — APPROVED** [review]
Given that we check time when meta.json file was uploaded, this makes sense to me. If we need to wait extra time when OOO blocks are uploaded, we can wait for a very long time.

File: pkg/compactor/job_test.go [hunk 1]
```diff
@@ -90,6 +96,15 @@ func TestJobWaitPeriodElapsed(t *testing.T) {
 			expectedElapsed: true,
 			expectedMeta:    nil,
 		},
+		"out of order block": {
+			waitPeriod: 10 * time.Minute,
+			jobBlocks: []jobBlock{
+				{meta: meta5, attrs: objstore.ObjectAttributes{LastModified: time.Now().Add(-20 * time.Minute)}},
+				{meta: meta6, attrs: objstore.ObjectAttributes{LastModified: time.Now().Add(-15 * time.Minute)}},
```
Comment (pracucci) [inline pkg/compactor/job_test.go:103]: Wouldn't this test pass anyway given the wait period is 10m but both meta5 and meta6 have been uploaded since more than 10m?

```suggestion
				{meta: meta6, attrs: objstore.ObjectAttributes{LastModified: time.Now().Add(-5 * time.Minute)}},
```

**Review by pracucci — APPROVED** [review]

File: pkg/compactor/job_test.go (hunk 1 above)
Comment (jhalterman) [reply pkg/compactor/job_test.go:103]: Well spotted
