### PR TITLE
mimirtool: Don't send template full path in 'alertmanager load'

### LINKED ISSUE #6137: The `mimirtool alertmanager load` sends full path of template files
#### Describe the bug

When using `mimirtool alertmanager load` command, I got the following error:

```log
mimirtool: error: POST request to http://mimir-gateway/api/v1/alerts failed: server returned HTTP status: 400 Bad Request, body: "error validating Alertmanager config: invalid template name \"/mnt/my-mimir-templates/my-template.tmpl\": the template name cannot contain any path\n", try --help
```

#### To Reproduce

1. Start Mimir (2.10.0)
2. Have templates stored in `/mnt/my-mimir-templates`
3. Run command:
   ```bash
   mimirtool alertmanager load --address http://mimir-gateway --id anonymous -- /tmp/config.yaml /mnt/my-mimir-templates/*.tmpl
   ```

#### Expected behavior

It uploads the Alertmanager config with the associated template.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

I'm running the command from a pod, and loading in my config and templates from configmaps. That's why my paths are weird (e.g `/mnt/...`)

### PR DESCRIPTION
**Pull request by jilleJr**
#### What this PR does

Makes sure templates sent to Mimir via the `mimirtool alertmanager load` command don't contain the full path, but instead only file name.

#### Which issue(s) this PR fixes or relates to

Fixes #6137

#### Checklist

- [x] Tests updated
- ~~Documentation added~~ (N/A)
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/mimirtool/commands/alerts_test.go [hunk 1]
```diff
@@ -0,0 +1,46 @@
+// SPDX-License-Identifier: AGPL-3.0-only
+// Provenance-includes-location: https://github.com/grafana/cortex-tools/blob/main/pkg/commands/alerts_test.go
+// Provenance-includes-license: Apache-2.0
+// Provenance-includes-copyright: The Cortex Authors.
```
Comment (dimitarvdimitrov) [inline pkg/mimirtool/commands/alerts_test.go:4]: Is this necessary? the code in this file seems authored by you and that cortex link doesn't eixst.

File: pkg/mimirtool/commands/alerts.go [hunk 2]
```diff
@@ -125,15 +126,28 @@ func (a *AlertmanagerCommand) readAlertManagerConfig() (string, map[string]strin
...
 	for _, f := range a.TemplateFiles {
 		tmpl, err := os.ReadFile(f)
 		if err != nil {
-			return "", nil, errors.Wrap(err, "unable to load template file: "+f)
+			return nil, errors.Wrap(err, "unable to load template file: "+f)
 		}
-		templates[f] = string(tmpl)
+		name := filepath.Base(f)
+		if _, ok := templates[name]; ok {
+			return nil, errors.New("cannot have multiple templates with same file names but different paths: "+f)
```
Comment (dimitarvdimitrov) [inline pkg/mimirtool/commands/alerts.go:146]: it's a shame we can't tell the user which files exactly are conflicting. I suppose just the base name should be enough

**Review by dimitarvdimitrov — COMMENTED** [review]
Thanks a lot for the contribution! I left a nitpick on the file header of alerts_test.go, but otherwise this is good to go

File: pkg/mimirtool/commands/alerts_test.go (hunk 1 above)
Comment (jilleJr) [reply pkg/mimirtool/commands/alerts_test.go:4]: I copied it from a different file. All the files in this directory had this, so I was unsure, and copied it over just in case.

Will remove.

File: pkg/mimirtool/commands/alerts.go (hunk 2 above)
Comment (jilleJr) [reply pkg/mimirtool/commands/alerts.go:146]: Good idea. I'll just add a little code to also track the original names.

File: CHANGELOG.md [hunk 3]
```diff
@@ -39,6 +39,7 @@
 * [BUGFIX] Fix out of bounds error on export with large timespans and/or series count. #5700
 * [BUGFIX] Fix the issue where `--read-timeout` was applied to the entire `mimirtool analyze grafana` invocation rather than to individual Grafana API calls. #5915
 * [BUGFIX] Fix incorrect remote-read path joining for `mimirtool remote-read` commands on Windows. #6009
+* [BUGFIX] Fix template files full path being sent in `mimirtool alertmanager load` command. #6137
```
Comment (dimitarvdimitrov) [inline CHANGELOG.md:42]:
```suggestion
* [BUGFIX] Fix template files full path being sent in `mimirtool alertmanager load` command. #6138
```

We use the id of the PR in the changelog entries

File: pkg/mimirtool/commands/alerts_test.go [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+		keys = append(keys, k)
+	}
+
+	assert.Equal(t, "alertmanager_template.tmpl", keys[0])
+	assert.NotEmpty(t, templates[keys[0]])
+}
+
+func TestReadAlertmanagerConfigTemplates_collidingNames(t *testing.T) {
+	cmd := AlertmanagerCommand{
+		TemplateFiles: []string {
```
Comment (dimitarvdimitrov) [inline pkg/mimirtool/commands/alerts_test.go:35]:
```suggestion
		TemplateFiles: []string{
```

File: pkg/mimirtool/commands/alerts_test.go [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func TestReadAlertmanagerConfigTemplates(t *testing.T) {
+	cmd := AlertmanagerCommand{
+		TemplateFiles: []string {
```
Comment (dimitarvdimitrov) [inline pkg/mimirtool/commands/alerts_test.go:14]:
```suggestion
		TemplateFiles: []string{
```

**Review by dimitarvdimitrov — APPROVED** [review]
Thanks for working on this! I left a couple of suggestions I'll automatically apply and then merge this
