### PR TITLE
compactor: fix flaky TestMultitenantCompactor_ShouldIncrementCompactionShutdownIfTheContextIsCancelled

### LINKED ISSUE #14689: Flaky TestMultitenantCompactor_ShouldIncrementCompactionShutdownIfTheContextIsCancelled
## `TestMultitenantCompactor_ShouldIncrementCompactionShutdownIfTheContextIsCancelled`

`pkg/compactor/compactor_test.go`

### About This Issue
This issue tracks a flaky test that has been detected failing inconsistently. Each week our analysis tool runs and detects this test as flaky, it will add a comment below with recent failure data and who might be able to help.

### 🔍 How to investigate
1. **Run it locally** to see if you can reproduce: `go test -count=10000 -run TestMultitenantCompactor_ShouldIncrementCompactionShutdownIfTheContextIsCancelled ./...`
2. **Check the failure logs** in the comments below - they might show a pattern
3. **Look for timing issues** - race conditions, timeouts, or external dependencies
4. **Review recent changes** - check commits that modified this test or the code under test recently

### 🎯 Next steps
- **Can you fix it?** Great! That would help the whole team
- **Need help?** Ask someone who has worked on this area recently
- **Can't fix it right now?** Consider adding logs and metrics so that next time it's easier to debug.
- **Obsolete test?** Maybe it's time to remove it or skip it with `t.Skip()`

_This test has been identified as flaky by [go-flaky-tests](https://github.com/grafana/shared-workflows/tree/main/actions/go-flaky-tests)._

### PR DESCRIPTION
**Pull request by AndrewCharlesHay**
#### What this PR does

Fixes a flaky test in the compactor package.

Commit af0592bd8b (`Compactor: Add 0-100% jitter to the first compaction interval`) introduced a variable first-tick interval using `DurationWithNegativeJitter(CompactionInterval, 1.0)`. With `variancePerc=1.0` the result is uniformly distributed in `[2 ns, CompactionInterval+1 ns]`, so on rare occasions the ticker fires almost immediately after the initial `compactUsers()` call returns. When that happens a second compaction run can start (and possibly complete) between the test's poll returning and `StopAndAwaitTerminated` cancelling the running context — breaking the test's assumption that exactly one run occurred.

The fix makes the test resilient to this intentional production behaviour:

- Replace `test.Poll(..., 1.0)` (exact equality) with `require.Eventually(..., >= 1)` so the poll still succeeds if a second run completes before the check.
- Replace exact-value `GatherAndCompare` assertions with invariant-based checks: `runs_started >= 1`, `runs_completed == 0`, `runs_erred == 0`, and `runs_started == runs_shutdown` (every run ended as a context-cancellation shutdown, not a success or unrelated error).

The test continues to verify the core property: when the planner returns `context.Canceled`, all compaction runs are counted as shutdowns and never as completions or errors.

#### Which issue(s) this PR fixes or relates to

Fixes #14689

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

---

> [!NOTE]
> **Low Risk**
> Low risk: changes are confined to a single unit test and only relax assertions to avoid flakiness from timing/jitter, without altering production code paths.
> 
> **Overview**
> Fixes flakiness in `TestMultitenantCompactor_ShouldIncrementCompactionShutdownIfTheContextIsCancelled` by no longer assuming exactly one compaction run occurs before shutdown.
> 
> The test now waits for `compactionRunsShutdown >= 1` and asserts metric *invariants* after stop (started >= 1, completed/erred == 0, and `started == shutdown`) instead of exact `GatherAndCompare` counters.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit b950ede11fef0cdd61a6ffd6f844b2f1384e29ca. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: pkg/compactor/compactor_test.go [hunk 1]
```diff
@@ -521,39 +521,32 @@ func TestMultitenantCompactor_ShouldIncrementCompactionShutdownIfTheContextIsCan
...
 	// Mock the planner as if a shutdown was triggered and the service was terminated.
 	tsdbPlannerMock.On("Plan", mock.Anything, mock.Anything).Return([]*block.Meta{}, context.Canceled)
 	require.NoError(t, services.StartAndAwaitRunning(context.Background(), c))
 
-	// Wait until the error is recorded.
-	test.Poll(t, time.Second, 1.0, func() interface{} {
-		return prom_testutil.ToFloat64(c.compactionRunsShutdown)
-	})
+	// Wait until at least one compaction run has been counted as shutdown. The variable
+	// first-tick interval introduced in the running() loop may cause a second run to
```
Comment (56quarters) [inline pkg/compactor/compactor_test.go]:
```suggestion
	// first-tick interval in the running() loop may cause a second run to
```
