### PR TITLE
storegateway: BucketChunkReader to validate chunk data length

### LINKED ISSUE #12691: store-gateway panics with "makeslice: len out of range"
### What is the bug?

We see occasional panics in store-gateway's `bucketChunkReader`

```
panic: runtime error: makeslice: len out of range
goroutine 147915604 [running]:
github.com/grafana/mimir/pkg/util/pool.(*SlabPool[...]).Get(0x22b3b10?, 0x12884816f240c?)
	/__w/backend-enterprise/backend-enterprise/vendor/github.com/grafana/mimir/pkg/util/pool/pool.go:67 +0x4c
github.com/grafana/mimir/pkg/util/pool.(*SafeSlabPool[...]).Get(0x41337d6500?, 0x4314c48?)
	/__w/backend-enterprise/backend-enterprise/vendor/github.com/grafana/mimir/pkg/util/pool/pool.go:123 +0xc4
github.com/grafana/mimir/pkg/storegateway.(*bucketChunkReader).loadChunks(0x40130728a0, {0x435ec30, 0x4046e08500}, {0x414fed8000, 0x242, 0x408c426f50?}, 0x4, {0x2774196, 0x2c1d5df, {0x0, ...}}, ...)
	/__w/backend-enterprise/backend-enterprise/vendor/github.com/grafana/mimir/pkg/storegateway/bucket_chunk_reader.go:150 +0x4fc
github.com/grafana/mimir/pkg/storegateway.(*bucketChunkReader).load.func3()
	/__w/backend-enterprise/backend-enterprise/vendor/github.com/grafana/mimir/pkg/storegateway/bucket_chunk_reader.go:100 +0x64
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/__w/backend-enterprise/backend-enterprise/vendor/golang.org/x/sync/errgroup/errgroup.go:93 +0x54
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 147915603
	/__w/backend-enterprise/backend-enterprise/vendor/golang.org/x/sync/errgroup/errgroup.go:78 +0x94
```

The relevant piece of code is here https://github.com/grafana/mimir/blob/db608fb47e884044689a8958aae5a0f2dbf0ff15/pkg/storegateway/bucket_chunk_reader.go#L148-L150

### How to reproduce it?

n/a

### What did you think would happen?

n/a

### What was your environment?

Kubernetes, jsonnet, mimir weekly r359

### Any additional context to share?

_No response_

### PR DESCRIPTION
**Pull request by narqo**
#### What this PR does

The PR adds a validation to the `BucketChunkReader` to make sure it doesn't panic, if the parsed chunk length exceed the allowed buffer length. See #12691 for the details.

#### Which issue(s) this PR fixes or relates to

Fixes #12691

#### Checklist

- [x] Tests updated.
- [ ] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by narqo** [comment]
> Do you have any idea how this is triggered?

I'm not sure. Initially, this looked like a corruption in transit. But there wasn't enough logs around the panic to double-check the actual TSDB. My hope is that the explicit error should give more clues.

File: pkg/storegateway/bucket_chunk_reader.go [hunk 1]
```diff
@@ -145,6 +145,14 @@ func (r *bucketChunkReader) loadChunks(ctx context.Context, res []seriesChunks,
 		if err != nil {
 			return errors.Wrap(err, "parsing chunk length")
 		}
+
+		// Validate chunk data length to prevent unreasonably large memory allocations or panics from a corrupted data.
+		// Note, that on a 64-bit system Go should allow to allocate up to 1<<47 bytes; a larger len causes "makeslice: len out of range".
+		// Such a large chunk data len is unrealistic. Here we're opting to a more conservative check.
+		if chunkDataLen > uint64(tsdb.EstimatedMaxChunkSize) {
```
Comment (dimitarvdimitrov) [inline pkg/storegateway/bucket_chunk_reader.go:152]: the estimated chunk size is just an estimation, there's nothing invalid in it. I thikn this pr introduces a bug. In fact, it's not uncommon for chunks to exceed this size

the issue you linked usually happens when the slice size is in the terrabytes or pteabytes of size. i would add some other kind of validation

Comment (dimitarvdimitrov) [reply pkg/storegateway/bucket_chunk_reader.go:152]: see docs on EstimatedMaxChunkSize

https://github.com/grafana/mimir/blob/a3076d1102ba4137c03ac8afd894f8b4c5eb6942/pkg/storage/tsdb/config.go#L61-L64
