### PR TITLE
querier: don't log errors on stream connection reset

### LINKED ISSUE #7023: Continuous  error logs  observed in mimir-querier service  when used without query-scheduler
#### Describe the bug
There's a lot of error logs in the querier service as soon as the chart was installed by using this [values file](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml) ,just couple of  changes-- s3 is added as backend, ingestor,storage gateway zone aware replication is false and query scheduler and alert manager are disabled and for resources allocation changes are made according to handle 1million by following this [file resources](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/small.yaml) ,that it. All the service are running with out no errors or atleast warnings except querier .
 

```
ts=2023-12-29T05:34:05.280080309Z caller=frontend_processor.go:89 level=error msg="error processing requests" address=10.90.10.260:9095 err="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR, debug data: \"max_age\""
ts=2023-12-29T05:34:05.28008376Z caller=frontend_processor.go:89 level=error msg="error processing requests" address=10.90.10.260:9095 err="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR, debug data: \"max_age\""
``` 

#### To Reproduce

1. Install the chart with attached values file, please change service account and s3 . 
2. Observe all the services will enter running state and Check the logs of querier.
3. Used values file  -[Values-mimir.txt](https://github.com/grafana/mimir/files/13791252/Values-mimir.txt)
4. Revision and version -- version=2.10.4, branch=r270, revision=297e905

#### Expected behavior

The querier service is filled with above error logs , and the endpoint it's pointing to is querier-frontend-headless which seems to be correct from helm chart as well. Not sure how to resolve this ,Any help is highly appreciated thanks ..!

#### Environment

- Infrastructure: [Kubernetes (eks)]
- Deployment tool: [helm]

#### Additional Context

Even though the querier service is filled with error of such , there's not issues observed while data queries or while loading dashboards in grafana.
It's observed  in all of our environments. No changes have been done on the env from mimir side like upgrade or any restart of pods are not  observed.

### PR DESCRIPTION
**Pull request by narqo**
#### What this PR does

If a gRPC server configured with `grpc_server_connection_max_age`, it closes the client's connections after a period of max_age + age_grace (refer to discussion https://github.com/grafana/mimir/issues/7023#issuecomment-1893752220).

At the moment there is nothing we expect a user to act on after the errors, the frontend- and scheduler-processors' client streams log, when the server resets the connection. This PR updates both processors, moving the logging to the debug level, to reduce any possible confusion.

_Sidenote: a more general solution, the gRPC folks suggested, is to implement an application specific lifetime management of the client stream. I.e. the stream's client should implement its own lifetime, to reconnect before the server drops it. So far, I'm not sure, it's worth the effort for the querier's use-case._

Also, the PR fixes some small inconsistencies in the related logs.

#### Which issue(s) this PR fixes or relates to

Fixes #7023

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/querier/worker/frontend_processor.go [hunk 1]
```diff
@@ -100,9 +99,9 @@ func (fp *frontendProcessor) processQueriesOnSingleStream(workerCtx context.Cont
 }
 
 // process loops processing requests on an established stream.
-func (fp *frontendProcessor) process(c frontendv1pb.Frontend_ProcessClient, address string, inflightQuery *atomic.Bool) (err error) {
+func (fp *frontendProcessor) process(execCtx context.Context, c frontendv1pb.Frontend_ProcessClient, address string, inflightQuery *atomic.Bool) (err error) {
 	// Build a child context so we can cancel a query when the stream is closed.
-	ctx, cancel := context.WithCancelCause(c.Context())
```
Comment (narqo) [inline pkg/querier/worker/frontend_processor.go:105]: Note, the [`grpc-go` docs mention that the `ClientStream.Context`][1]:

> ... should not be called until after Header or RecvMsg has returned. Once called, subsequent client-side retries are disabled.

I don't think this cases any issues, as this one was here for several years. That is, I consider this a "code clean-up", rather than a "fix".

[1]: https://pkg.go.dev/google.golang.org/grpc#ClientStream.Context

Comment (dimitarvdimitrov) [reply pkg/querier/worker/frontend_processor.go:105]: does this change now mean that the frontend might cancel the stream, but we wouldn't know about it? This is the code in the frontend.

https://github.com/grafana/mimir/blob/e14de9592b4e19a69139a2d49447c789f679bf0f/pkg/frontend/v1/frontend.go#L270-L274

I'm slightly surprised no tests failed :/

Comment (narqo) [reply pkg/querier/worker/frontend_processor.go:105]: I believe it should work just fine. That is, consider the following scenario:

```
client → frontend → querier → backend
```

1. When a client cancels their request, the frontend closes its side of the stream, returning the `context.Cancel` wrapped into an RPC-error, to the querier's side of the stream. 
2. The processing loop inside the querier will `Receive` this error and bail out.
3. This will close the local context inside the `frontendProcessor.process()`, thanks to `defer cancel()`.
4. An in-flight request to the backend will be notified about the cancellation in (3).

Note, I've now looked through the tests in `querier/worker`, and added some cosmetic changes. The overall behaviour shouldn't have changed.

Comment (dimitarvdimitrov) [reply pkg/querier/worker/frontend_processor.go:105]: makes sense, I had missed the `defer cancel()`

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, thanks for fixing this!
