### PR TITLE
Remote execution: fix issue where labels can be corrupted

### LINKED ISSUE #12982: Flaky TestMaxQueryParallelismWithRemoteExecution
## `TestMaxQueryParallelismWithRemoteExecution`

`pkg/frontend/v2/remoteexec_test.go`

### About This Issue
This issue tracks a flaky test that has been detected failing inconsistently. Each week our analysis tool runs and detects this test as flaky, it will add a comment below with recent failure data and who might be able to help.

### 🔍 How to investigate
1. **Run it locally** to see if you can reproduce: `go test -count=10000 -run TestMaxQueryParallelismWithRemoteExecution ./...`
2. **Check the failure logs** in the comments below - they might show a pattern
3. **Look for timing issues** - race conditions, timeouts, or external dependencies
4. **Review recent changes** - check commits that modified this test or the code under test recently

### 🎯 Next steps
- **Can you fix it?** Great! That would help the whole team
- **Need help?** Ask someone who has worked on this area recently
- **Can't fix it right now?** Consider adding logs and metrics so that next time it's easier to debug.
- **Obsolete test?** Maybe it's time to remove it or skip it with `t.Skip()`

_This test has been identified as flaky by [go-flaky-tests](https://github.com/grafana/shared-workflows/tree/main/actions/go-flaky-tests)._

### PR DESCRIPTION
**Pull request by charleskorn**
#### What this PR does

This PR fixes an issue where queries evaluated with remote execution can have corrupted labels.

This occurred when the underlying buffer for the gRPC message containing the labels was reused before the labels could be converted to a `labels.Labels` instance by `mimirpb.FromLabelAdaptersToLabels`.

This PR also fixes an issue where `TestMaxQueryParallelismWithRemoteExecution` can flake (resolves #12982), as it was consistently flaking with the change to use a real gRPC stream in the tests.

I would recommend reviewing each commit separately.

#### Which issue(s) this PR fixes or relates to

(none)

#### Checklist

- [x] Tests updated.
- [n/a] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

**Comment by dimitarvdimitrov** [comment]
:robot: _Automated comment_ <br><br>The CHANGELOG has just been cut to prepare for the next release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG.md document. Thanks!

File: pkg/frontend/v2/frontend_test.go [hunk 1]
```diff
@@ -64,22 +66,35 @@ func setupFrontend(t testing.TB, reg prometheus.Registerer, schedulerReplyFunc f
...
+	frontendListener, err := net.Listen("tcp", "localhost:0")
 	require.NoError(t, err)
 
-	server := grpc.NewServer(opts...)
+	schedulerListener, err := net.Listen("tcp", "localhost:0")
+	require.NoError(t, err)
+
+	schedulerOpts := opts
+	frontendOpts := append(
+		opts,
```
Comment (56quarters) [inline pkg/frontend/v2/frontend_test.go]: Won't this use the memory from `opts` if it has enough space for the additional interceptors? It's not clear to me if this will end up modifying `schedulerOpts`.

File: pkg/frontend/v2/frontend_test.go [hunk 2]
```diff
@@ -1313,6 +1315,79 @@ func TestFrontend_Protobuf_ResponseWithUnexpectedUserID(t *testing.T) {
...
+
+				resp.Close()
+			}
+		})
+	}
+
+	wg.Wait()
+}
+
+func generateConcurrencyTestResponse(idx uint64) *frontendv2pb.QueryResultStreamRequest {
```
Comment (56quarters) [inline pkg/frontend/v2/frontend_test.go:1396]: There's a surprising amount of things going on in this method. Can you add some comments that explain why we're generating each of these labels for a particular response?

File: pkg/frontend/v2/remoteexec.go [hunk 3]
```diff
@@ -123,11 +123,14 @@ type scalarExecutionResponse struct {
...
 
 func (r *scalarExecutionResponse) GetValues(ctx context.Context) (types.ScalarData, error) {
-	resp, err := readNextEvaluateQueryResponse(ctx, r.stream)
+	resp, releaseMessage, err := readNextEvaluateQueryResponse(ctx, r.stream)
 	if err != nil {
 		return types.ScalarData{}, err
 	}
 
+	// Nothing in the message retains a reference to the underlying buffer, so we can release it immediately.
+	releaseMessage()
```
Comment (56quarters) [inline pkg/frontend/v2/remoteexec.go]: I don't really like that we're asserting that we can immediately free the buffer associated with this message. It seems like it would be more correct to always `defer releaseMessage()` so that we aren't encoding how the query response message works here.

**Review by 56quarters — APPROVED** [review]
LGTM with some non-blocking comments.

File: pkg/frontend/v2/remoteexec.go (hunk 3 above)
Comment (charleskorn) [reply pkg/frontend/v2/remoteexec.go]: Good point, fixed in 03cecbc.

File: pkg/frontend/v2/frontend_test.go (hunk 2 above)
Comment (charleskorn) [reply pkg/frontend/v2/frontend_test.go:1396]: I've added some explanation in 34ae032 - how's that?

File: pkg/frontend/v2/frontend_test.go (hunk 1 above)
Comment (charleskorn) [reply pkg/frontend/v2/frontend_test.go]: I think this is safe, but I'll add a clone here to make it very clear what the intention is.

Comment (charleskorn) [reply pkg/frontend/v2/frontend_test.go]: Done in 8df0e7f.
