### PR TITLE
Distributor: make OTLP endpoint return marshalled proto bytes as response body for errors

### LINKED ISSUE #8185: otlp: Mimir's OTLP endpoint to return marshalled proto bytes as response body
#### Describe the bug

The handler that wraps around the otlp endpoint on distributors [replies with a normal string in the body](https://github.com/grafana/mimir/blob/main/pkg/distributor/push.go#L158-L179) which is the normal behavior for all Mimir endpoints but its not what the otel spec defines.

In https://opentelemetry.io/docs/specs/otlp/#failures-1 we can see that:

> If the processing of the request fails, the server MUST respond with appropriate HTTP 4xx or HTTP 5xx status code. See the sections below for more details about specific failure cases and HTTP status codes that should be used.
> 
> The response body for all HTTP 4xx and HTTP 5xx responses MUST be a Protobuf-encoded [Status](https://godoc.org/google.golang.org/genproto/googleapis/rpc/status#Status) message that describes the problem.If the processing of the request fails, the server MUST respond with appropriate HTTP 4xx or HTTP 5xx status code. See the sections below for more details about specific failure cases and HTTP status codes that should be used.
> 
> The response body for all HTTP 4xx and HTTP 5xx responses MUST be a Protobuf-encoded [Status](https://godoc.org/google.golang.org/genproto/googleapis/rpc/status#Status) message that describes the problem.

Since Mimir only supports otlp through HTTP we can go to the otlphttpexporter in the collector and confirm that the client is expecting this marshaled proto of the Status struct [here](https://github.com/open-telemetry/opentelemetry-collector/blob/05867e63ac871040b790d91ffb85efdc4148b45f/exporter/otlphttpexporter/otlp.go#L281-L286)

```golang
		// Decode it as Status struct. See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#failures
		respStatus = &status.Status{}
		err = proto.Unmarshal(respBytes, respStatus)
		if err != nil {
			return nil
		}
```

Now because Mimir replies with a normal string instead of whats expected by the client and spec, when collectors write to Mimir and there is a 400 error the entire error message by Mimir does not appear in the collector logs making it very hard to troubleshoot the original issue
```
Exporting failed. Dropping data. {"kind": "exporter", "datatype": "metrics", "name": "otlphttp", "error": "not retryable error: Permanent error: error exporting items, request to https://otlp-gateway-prod-us-east-0.grafana.net/otlp/v1/metri cs responded with HTTP Status Code 400", "droppeditems": 505}
```

#### To Reproduce

1. Start latest Mimir
2. Write a metric through the otlp endpoint with an attribute value longer than Mimir's 2048 byte limit.
3. You'll see that the response you get is a normal body string instead of marshalled proto bytes.

Example script to reproduce this behavior
```
now=$(date +%s)

data="
{
    \"resourceMetrics\": [
      {
        \"resource\": {
          \"attributes\": [
            {
              \"key\": \"service.name\",
              \"value\": {
                \"stringValue\": \"amuwpkjykzrnguttaduwkqrdyiwhbpuaqjrgexjzzcwrqvnukgtwhrwacfmqgwvvrhpvqqieahfzjcherahydcqcprwcqxeytmbhrkaauxccgcqrvmpyvbmijawiizftmrktukfyqwmnuxxbrjtifigqrhyhcyaxwppkidvvjjaqevepxefbxpyezumyqyecttnvprruqyjrcarhwbtjqpwqpewmdfmexuthdgegrpnbnjdqxmgguyzmqtahgfmedctgzjapfpgtdmmgjikgmqvybpaezvveergkqqqjaymkxnhezhbrrhyypygvjvjpmekivhhfvftbhwzyxbrbemxyhwfpefzxmzhafzjnwyjgtkmcfdbveqagmkvcnfpexcaqamzvntptdfqvpdbcdbwgpdcrdmendmpyyerfurdhjhvtpfkvcnjqbvuyqpaqkiedkavtmnvznxhqynivriymuevdhdyauviahybgbnbudxrhybfbuabrjazgmmwjzgpwhnurtfaqqkgrvpyqexvggmwxqznhwxxfgeyewixaafynbmytijqyarkahwhghbujakdrarkyjxpjnfrxgnmvgvviikhfrgqxmkufxgxijrnuezefiwibqwpxjcqgqaafawwhmbbyynkbhadpjmmytrqtcwepnpfpmktxmnqjcradypktaupyikbcfccayxdxkvjuhkuiqxkahmwwxeqtnxhknzwuxrewnimwpavqtxxbqiytxityvfxawbiqzqphfkxgrkcwbdhepdygpyjhnpcagfqvepfkpywmbehqdbtvbqzbjjhgpgcejhyvceibtkhyxvrzmvghepubvdhvxuytdewuggypwarqzmujhgvaggzhyvmfnpzkwfkenhrjkruafyrivjzajntaykgmuccxrvrgtqtwfixnbpiyfcgdhxvenjguwxgghjixuhvdukjyamrtwazcbqixeywnbthycuafhahzkfqqwujkpizkcgcdivyxjjgwqixfbyrwpmfdbakrpqfzhamizbirmfjajkncjufiwveigvvzzrqbkebayfpgerjcjvwzuvxuwtxradqugizdubwupcvtqtvprwkwdpecnunuhmgnwvtmkcvrhmeanmccccdzhbprfijxdaykbizzmmyckatdmkxrpfgjndwymvabctfjmbimrjrpyqiiygeidcadgrhucqegwjqthbbewqutmjkcdwedzpidjhrjnikjkbbuebfrjmkkcupagxbmqjvtytuinbzupzqianuxgjahrfhkymuucamhfqbqcerzzbwfzikcryigzthehvajzmcecvbhzcuripfhaekknzevipdwuchatzpjnchrzbfihdiubtyxkqhxzbwkjffzygrhnbfgcnhxfayzeduxvnndktwhxqgbtumphrnxncqqedbyceupniktpytejicqpbpvhkqewegztrfigzguygidpbiguvydnkkbknxxzzjcfaayaihxampaknbjmvcndifdunkgymuwmcxcjhpfdzhnkvtcgexxmkhkmikcwnqimxbvijmkhfmurwneedibzbywxppvwukphpeazuchiqxyhavnjbjpibaxnxfaxgkvrdvjvtunnahexgjjexzkntzzcwuazfebregacfibknkyqqkywjxrmadnfwgzpftyigzgxdhgwdcdjqgnkhrxznbwcdgugemffdfvruivjjazuhbrhyxeuegyynmggcxjyxyfzuggzwvfqedgqngpkfkwrvbpqwywjzbifdquzhqtujqvrwhzpqvakbybaxfhwecajrhwhibzukjxymabcdwxymxtznjipfnmwqczddxrvxaktcbnhvwnxjrcfzeabiqyecqnuqberahtabivwkrvdkqjpevxmkejynuxwbmdadbtzxejfuxrvenemubqtrihuzwjakjrpgexwixgutdvcqkdtfpbujiayibfvhfdmtucvahfjhfvdpfjbgumgkafkyprgyjirvzhfaziyqahw\"
              }
            }
          ]
        },
        \"scopeMetrics\": [
          {
            \"metrics\": [
              {
                \"name\": \"your_test_metric\",
                \"unit\": \"s\",
                \"description\": \"\",
                \"gauge\": {
                  \"dataPoints\": [
                    {
                      \"asInt\": 1,
                      \"timeUnixNano\": ${now}000000000
                    }
                  ]
                }
              }
            ]
          }
        ]
      }
    ]
  }
"


curl \
  -k \
  -i \
  -XPOST \
  -H 'Content-Type: application/json' \
  -u "${tenant}:${apikey}" \
    https://mimir-address:port/otlp/v1/metrics -d "${data}"
``` 

And here a example run
```
❯ bash send-metric-that-fails.sh
HTTP/2 400
content-length: 668
content-type: text/plain; charset=utf-8
date: Mon, 27 May 2024 09:26:09 GMT
server: envoy
x-content-type-options: nosniff
x-envoy-upstream-service-time: 104
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

received a series whose label value length exceeds the limit, label: 'job', value: 'amuwpkjykzrnguttaduwkqrdyiwhbpuaqjrgexjzzcwrqvnukgtwhrwacfmqgwvvrhpvqqieahfzjcherahydcqcprwcqxeytmbhrkaauxccgcqrvmpyvbmijawiizftmrktukfyqwmnuxxbrjtifigqrhyhcyaxwppkidvvjjaqevepxefbxpyezumyqyecttnvprru' (truncated) series: 'jesus_test_metric_seconds{job="amuwpkjykzrnguttaduwkqrdyiwhbpuaqjrgexjzzcwrqvnukgtwhrwacfmqgwvvrhpvqqieahfzjcherahydcqcprwcqxeytmbhrkaauxccgcqrvmpyvbmijawiizftmrktukfyqwmnuxxbrjtifigqrhyhcyaxwppkidvvj' (err-mimir-label-value-too-long). To adjust the related per-tenant limit, configure -validation.max-length-label-value, or contact your service administrator.
```

#### Expected behavior

The endpoint should reply with marshaled proto bytes and then we should expect to see the concise mimir errors on the collector logs.

### PR DESCRIPTION
**Pull request by ying-jeanne**
#### Which issue(s) this PR fixes or relates to

Fixes #8185 , as discussed there are 2 possible ways to solve this:
- pass a error handling function to handler, have 2 different implementation for otlp and normal push request
- replicate the handler function for otlp and normal push request.

This PR is using the 2nd solution since it allows us to have more different logics for otlp endpoint in the future.

#### Checklist

- [x] Tests updated.
- [x] Documentation added.
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [x] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

### CODE REVIEW

File: pkg/distributor/push.go [hunk 1]
```diff
@@ -180,6 +185,93 @@ func handler(
...
+				// Check for httpgrpc error, default to client error if parsing failed
+				if _, ok := httpgrpc.HTTPResponseFromError(err); !ok {
+					err = httpgrpc.Errorf(http.StatusBadRequest, err.Error())
+				}
+
+				rb.CleanUp()
+				return nil, nil, err
+			}
+
+			if allowSkipLabelNameValidation {
```
Comment (jesusvazquez) [inline pkg/distributor/push.go:221]: I don't think we need this here. The reason this exists in the other distributor endpoints is because of the graphite proxy that writes some strange characters.

For otel we can get rid of it 👍

**Review by jesusvazquez — CHANGES_REQUESTED** [review]
Requesting small change other than that looks good to me.

I do think that this will solve the issue but we still have to work more on the errors. For example returning this:
```
the incoming push request has been rejected because its message size is larger than the allowed limit of 140 bytes (err-mimir-distributor-max-write-message-size). To adjust the related limit, configure -distributor.max-recv-msg-size, or contact your service administrator.
```

To the user explains the error in Mimir but it doesnt explain how to fix it in the collector. This is the bridge that we have to fix. But lets do that in future PRs not on this one 👍

**Comment by ying-jeanne** [comment]
> Requesting small change other than that looks good to me.
> 
> I do think that this will solve the issue but we still have to work more on the errors. For example returning this:
> 
> ```
> the incoming push request has been rejected because its message size is larger than the allowed limit of 140 bytes (err-mimir-distributor-max-write-message-size). To adjust the related limit, configure -distributor.max-recv-msg-size, or contact your service administrator.
> ```
> 
> To the user explains the error in Mimir but it doesnt explain how to fix it in the collector. This is the bridge that we have to fix. But lets do that in future PRs not on this one 👍

Thanks @jesusvazquez for the review, I have this ticket to track all the rest we needs in order to support otlp endpoint, attached another ticket with your description in it.

File: pkg/distributor/push.go (hunk 1 above)
Comment (ying-jeanne) [reply pkg/distributor/push.go]: removed

File: pkg/distributor/push.go [hunk 2]
```diff
@@ -169,7 +173,8 @@ func handler(
 			if resp, ok := httpgrpc.HTTPResponseFromError(err); ok {
 				code, msg = int(resp.Code), string(resp.Body)
 			} else {
-				code, msg = toHTTPStatus(ctx, err, limits), err.Error()
+				_, code = toGRPCHTTPStatus(ctx, err, limits)
```
Comment (jesusvazquez) [inline pkg/distributor/push.go:176]: You might want the grpc error code for the logline below.

**Review by jesusvazquez — APPROVED** [review]
LGTM left a small note but is no blocker

File: pkg/distributor/push.go (hunk 2 above)
Comment (ying-jeanne) [reply pkg/distributor/push.go:176]: this is not used by normal mimir handler, i would just leave it as right now.

**Review by johannaratliff — APPROVED** [review]
LGTM I'll defer to @jesusvazquez 's expertise on the primary functionality here being good

File: pkg/distributor/push_test.go [hunk 3]
```diff
@@ -1178,7 +1186,7 @@ func TestHandler_ToHTTPStatus(t *testing.T) {
 			)
 			require.NoError(t, err)
 
-			status := toHTTPStatus(ctx, tc.err, limits)
+			_, status := toGRPCHTTPStatus(ctx, tc.err, limits)
```
Comment (56quarters) [inline pkg/distributor/push_test.go:1189]: We should be asserting the gRPC code too if we're using the same method to generate them and HTTP codes. Either that or we should split the error translation methods.

File: pkg/distributor/push.go [hunk 4]
```diff
@@ -198,19 +290,19 @@ func calculateRetryAfter(retryAttemptHeader string, baseSeconds int, maxBackoffE
...
 }
 
-// toHTTPStatus converts the given error into an appropriate HTTP status corresponding
-// to that error, if the error is one of the errors from this package. Otherwise, an
+// toGRPCHTTPStatus converts the given error into an appropriate GRPC and HTTP status corresponding
+// to that error, if the error is one of the errors from this package. Otherwise, codes.Internal and
 // http.StatusInternalServerError is returned.
-func toHTTPStatus(ctx context.Context, pushErr error, limits *validation.Overrides) int {
+func toGRPCHTTPStatus(ctx context.Context, pushErr error, limits *validation.Overrides) (codes.Code, int) {
 	if errors.Is(pushErr, context.DeadlineExceeded) {
```
Comment (56quarters) [inline pkg/distributor/push.go:297]: nit: this conditionally isn't really needed since this is the default return at the bottom of the function.

**Review by 56quarters — APPROVED** [review]
OK to merge but there are a few changes I'd like to see made or ticketed as follow up work for next week.

File: pkg/distributor/push.go [hunk 5]
```diff
@@ -180,6 +185,93 @@ func handler(
...
+		}
+	})
+}
+
+// writeErrorToHTTPResponseBody converts the given error into a grpc status and marshals it into a byte slice, in order to be written to the response body.
+// See doc https://opentelemetry.io/docs/specs/otlp/#failures-1
+func writeErrorToHTTPResponseBody(w http.ResponseWriter, httpCode int, grpcCode codes.Code, msg string, logger log.Logger) {
+	// writeResponseFailedError would be returned when writeErrorToHTTPResponseBody fails to write the error to the response body.
+	writeResponseFailedBody, _ := proto.Marshal(grpcstatus.New(codes.Internal, "write error to response failed").Proto())
+	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
```
[the remark this answers is not in the document]
Comment (ying-jeanne) [reply pkg/distributor/push.go:258]: changed to application/octet-stream

File: pkg/distributor/push.go (hunk 4 above)
Comment (ying-jeanne) [reply pkg/distributor/push.go:297]: let me do it in a separate PR, since this is not related to the otlp change, don't want to break the code in push.

File: pkg/distributor/push.go [hunk 6]
```diff
@@ -180,6 +185,93 @@ func handler(
...
+			addHeaders(w, err, r, httpCode, retryCfg)
+		}
+	})
+}
+
+// writeErrorToHTTPResponseBody converts the given error into a grpc status and marshals it into a byte slice, in order to be written to the response body.
+// See doc https://opentelemetry.io/docs/specs/otlp/#failures-1
+func writeErrorToHTTPResponseBody(w http.ResponseWriter, httpCode int, grpcCode codes.Code, msg string, logger log.Logger) {
+	// writeResponseFailedError would be returned when writeErrorToHTTPResponseBody fails to write the error to the response body.
+	writeResponseFailedBody, _ := proto.Marshal(grpcstatus.New(codes.Internal, "write error to response failed").Proto())
```
Comment (pstibrany) [inline pkg/distributor/push.go:257]: We always marshal this message even if it's not used. We could actually just marshal it once and resue for every call.

File: pkg/distributor/push.go [hunk 7]
```diff
@@ -180,6 +185,93 @@ func handler(
...
+				s, _ := grpcutil.ErrorToStatus(err)
+				writeErrorToHTTPResponseBody(w, int(resp.Code), s.Code(), string(resp.Body), logger)
+			} else {
+				grpcCode, httpCode = toGRPCHTTPStatus(ctx, err, limits)
+				writeErrorToHTTPResponseBody(w, httpCode, grpcCode, err.Error(), logger)
+			}
+			if httpCode != 202 {
+				level.Error(logger).Log("msg", "push error", "err", err)
+			}
+			addHeaders(w, err, r, httpCode, retryCfg)
```
Comment (pstibrany) [inline pkg/distributor/push.go:248]: Adding headers here is too late -- headers were already written to client by this time. It means responses will not have correct `Retry-After` headers.

File: pkg/distributor/push.go [hunk 8]
```diff
@@ -180,6 +185,93 @@ func handler(
...
+				return
+			}
+			var (
+				httpCode int
+				grpcCode codes.Code
+			)
+			if resp, ok := httpgrpc.HTTPResponseFromError(err); ok {
+				// here the error would always be nil, since it is already checked in httpgrpc.HTTPResponseFromError
+				s, _ := grpcutil.ErrorToStatus(err)
+				writeErrorToHTTPResponseBody(w, int(resp.Code), s.Code(), string(resp.Body), logger)
```
Comment (pstibrany) [inline pkg/distributor/push.go:240]: This means we're passing HTTP status code as grpc code. Can OTLP clients handle that? (Abusing http codes as grpc codes is something we do in our code, but I don't think we should send it to clients expecting grpc response)

File: pkg/distributor/push.go (hunk 6 above)
Comment (pstibrany) [reply pkg/distributor/push.go:257]: I've changed this in #8294.

File: pkg/distributor/push.go (hunk 7 above)
Comment (pstibrany) [reply pkg/distributor/push.go:248]: Fixing this in #8294.
